import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const REGISTRY_PATH = 'docs/gameplay/rule-evidence.json';
const GENERATED_PATH = 'docs/quality/gameplay-rule-evidence.md';
const WRITE = process.argv.includes('--write');

const EVIDENCE_LEVELS = new Set(['E0', 'E1', 'E2', 'E3', 'E4', 'E5', 'E6']);
const STATUSES = new Set(['aligned', 'partial', 'divergent', 'unverified']);
const FORMALIZATIONS = new Set([
  'assignment',
  'equation',
  'equivalence',
  'function',
  'inequality',
  'invariant',
  'metamorphic',
  'noninterference',
  'policy',
  'predicate',
  'proof',
  'protocol',
  'recurrence',
  'relation',
  'schema',
  'sequence',
  'transition',
]);

interface RuleEvidence {
  id: string;
  section: string;
  sourceMarker: string;
  claim: string;
  formalization: string;
  evidence: string;
  status: string;
  implementation: string[];
  verification: string[];
}

interface Registry {
  registryVersion: number;
  rulesVersion: string;
  normativeSource: string;
  rules: RuleEvidence[];
}

function absolute(path: string): string {
  return resolve(process.cwd(), path);
}

function read(path: string): string {
  return readFileSync(absolute(path), 'utf8');
}

function escapeCell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function render(registry: Registry): string {
  const counts = new Map<string, number>();
  for (const rule of registry.rules) counts.set(rule.status, (counts.get(rule.status) ?? 0) + 1);

  const rows = registry.rules.map((rule) => {
    const implementation = rule.implementation.map((path) => `\`${path}\``).join('<br>') || '—';
    const verification = rule.verification.map((path) => `\`${path}\``).join('<br>') || '—';
    return `| ${rule.id} | §${rule.section} | ${escapeCell(rule.claim)} | ${rule.formalization} | ${rule.evidence} | ${rule.status} | ${implementation} | ${verification} |`;
  });

  return `<!-- GENERATED by scripts/ci/verify-rule-evidence.ts --write; do not edit -->
# Gameplay Rule Evidence

Rules version: \`${registry.rulesVersion}\`

Registry version: \`${registry.registryVersion}\`

This is a generated traceability view of
\`${registry.normativeSource}\`. Status is qualified by evidence level: an
\`E1 aligned\` claim has representative examples, not exhaustive proof.

## Current Summary

| Status | Count |
|---|---:|
| aligned | ${counts.get('aligned') ?? 0} |
| partial | ${counts.get('partial') ?? 0} |
| divergent | ${counts.get('divergent') ?? 0} |
| unverified | ${counts.get('unverified') ?? 0} |

## Registry

| Rule | Source | Claim | Formalization | Evidence | Status | Implementation | Verification |
|---|---:|---|---|---:|---|---|---|
${rows.join('\n')}

## Interpretation

- \`E0\`: assertion only
- \`E1\`: representative example evidence
- \`E2\`: generated property evidence
- \`E3\`: exhaustive finite-domain evidence
- \`E4\`: formal proof or model-check evidence
- \`E5\`: preregistered statistical evidence
- \`E6\`: operational observation

See \`docs/reference/gameplay-assurance.md\` for scope and completion semantics.
`;
}

const failures: string[] = [];

if (!existsSync(absolute(REGISTRY_PATH))) failures.push(`missing registry: ${REGISTRY_PATH}`);

let registry: Registry | undefined;
if (failures.length === 0) {
  try {
    registry = JSON.parse(read(REGISTRY_PATH)) as Registry;
  } catch (error) {
    failures.push(`invalid JSON in ${REGISTRY_PATH}: ${String(error)}`);
  }
}

if (registry) {
  if (!Number.isInteger(registry.registryVersion) || registry.registryVersion < 1) {
    failures.push('registryVersion must be a positive integer');
  }
  if (!existsSync(absolute(registry.normativeSource))) {
    failures.push(`missing normative source: ${registry.normativeSource}`);
  }

  const normative = existsSync(absolute(registry.normativeSource))
    ? read(registry.normativeSource)
    : '';
  const seen = new Set<string>();

  registry.rules.forEach((rule, index) => {
    const expected = `PD-RULE-${String(index + 1).padStart(3, '0')}`;
    if (rule.id !== expected)
      failures.push(`rule ${index + 1}: expected ${expected}, got ${rule.id}`);
    if (seen.has(rule.id)) failures.push(`duplicate rule id: ${rule.id}`);
    seen.add(rule.id);

    if (!rule.claim.trim()) failures.push(`${rule.id}: claim must not be empty`);
    if (!normative.includes(rule.sourceMarker)) {
      failures.push(
        `${rule.id}: normative source missing marker ${JSON.stringify(rule.sourceMarker)}`,
      );
    }
    if (!FORMALIZATIONS.has(rule.formalization)) {
      failures.push(`${rule.id}: unknown formalization ${rule.formalization}`);
    }
    if (!EVIDENCE_LEVELS.has(rule.evidence)) {
      failures.push(`${rule.id}: unknown evidence level ${rule.evidence}`);
    }
    if (!STATUSES.has(rule.status)) failures.push(`${rule.id}: unknown status ${rule.status}`);
    if (rule.evidence !== 'E0' && rule.verification.length === 0) {
      failures.push(`${rule.id}: ${rule.evidence} requires at least one verification reference`);
    }
    for (const path of [...rule.implementation, ...rule.verification]) {
      if (!existsSync(absolute(path)))
        failures.push(`${rule.id}: referenced file does not exist: ${path}`);
    }
  });

  if (registry.rules.length !== 63) {
    failures.push(`expected 63 registered rules, found ${registry.rules.length}`);
  }

  const generated = render(registry);
  if (WRITE) {
    writeFileSync(absolute(GENERATED_PATH), generated);
    console.log(`Wrote ${GENERATED_PATH}`);
  } else if (!existsSync(absolute(GENERATED_PATH))) {
    failures.push(`missing generated traceability view: ${GENERATED_PATH}`);
  } else if (read(GENERATED_PATH) !== generated) {
    failures.push(`${GENERATED_PATH} is stale; run pnpm rules:evidence:write`);
  }
}

if (failures.length > 0) {
  console.error('Rule evidence verification failed:');
  for (const failure of failures) console.error(`- ${failure}`);
  process.exit(1);
}

if (!WRITE)
  console.log(`Rule evidence verification passed (${registry?.rules.length ?? 0} rules).`);
