/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// SocialAPIService SocialAPI service
type SocialAPIService service

type SocialAPIApiMatchesMatchIdCommentsGetRequest struct {
	ctx context.Context
	ApiService *SocialAPIService
	matchId string
}

func (r SocialAPIApiMatchesMatchIdCommentsGetRequest) Execute() ([]ApiMatchesMatchIdCommentsGet200ResponseInner, *http.Response, error) {
	return r.ApiService.ApiMatchesMatchIdCommentsGetExecute(r)
}

/*
ApiMatchesMatchIdCommentsGet Get comments for a match

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param matchId
 @return SocialAPIApiMatchesMatchIdCommentsGetRequest
*/
func (a *SocialAPIService) ApiMatchesMatchIdCommentsGet(ctx context.Context, matchId string) SocialAPIApiMatchesMatchIdCommentsGetRequest {
	return SocialAPIApiMatchesMatchIdCommentsGetRequest{
		ApiService: a,
		ctx: ctx,
		matchId: matchId,
	}
}

// Execute executes the request
//  @return []ApiMatchesMatchIdCommentsGet200ResponseInner
func (a *SocialAPIService) ApiMatchesMatchIdCommentsGetExecute(r SocialAPIApiMatchesMatchIdCommentsGetRequest) ([]ApiMatchesMatchIdCommentsGet200ResponseInner, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []ApiMatchesMatchIdCommentsGet200ResponseInner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SocialAPIService.ApiMatchesMatchIdCommentsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/matches/{matchId}/comments"
	localVarPath = strings.Replace(localVarPath, "{"+"matchId"+"}", url.PathEscape(parameterValueToString(r.matchId, "matchId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SocialAPIApiMatchesMatchIdCommentsPostRequest struct {
	ctx context.Context
	ApiService *SocialAPIService
	matchId string
	apiMatchesMatchIdCommentsPostRequest *ApiMatchesMatchIdCommentsPostRequest
}

func (r SocialAPIApiMatchesMatchIdCommentsPostRequest) ApiMatchesMatchIdCommentsPostRequest(apiMatchesMatchIdCommentsPostRequest ApiMatchesMatchIdCommentsPostRequest) SocialAPIApiMatchesMatchIdCommentsPostRequest {
	r.apiMatchesMatchIdCommentsPostRequest = &apiMatchesMatchIdCommentsPostRequest
	return r
}

func (r SocialAPIApiMatchesMatchIdCommentsPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApiMatchesMatchIdCommentsPostExecute(r)
}

/*
ApiMatchesMatchIdCommentsPost Add a comment to a match

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param matchId
 @return SocialAPIApiMatchesMatchIdCommentsPostRequest
*/
func (a *SocialAPIService) ApiMatchesMatchIdCommentsPost(ctx context.Context, matchId string) SocialAPIApiMatchesMatchIdCommentsPostRequest {
	return SocialAPIApiMatchesMatchIdCommentsPostRequest{
		ApiService: a,
		ctx: ctx,
		matchId: matchId,
	}
}

// Execute executes the request
func (a *SocialAPIService) ApiMatchesMatchIdCommentsPostExecute(r SocialAPIApiMatchesMatchIdCommentsPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SocialAPIService.ApiMatchesMatchIdCommentsPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/matches/{matchId}/comments"
	localVarPath = strings.Replace(localVarPath, "{"+"matchId"+"}", url.PathEscape(parameterValueToString(r.matchId, "matchId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiMatchesMatchIdCommentsPostRequest == nil {
		return nil, reportError("apiMatchesMatchIdCommentsPostRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiMatchesMatchIdCommentsPostRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiMatchesMatchIdVerifyGet404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SocialAPIApiMatchesMatchIdFavoriteDeleteRequest struct {
	ctx context.Context
	ApiService *SocialAPIService
	matchId string
}

func (r SocialAPIApiMatchesMatchIdFavoriteDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApiMatchesMatchIdFavoriteDeleteExecute(r)
}

/*
ApiMatchesMatchIdFavoriteDelete Unfavorite a match

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param matchId
 @return SocialAPIApiMatchesMatchIdFavoriteDeleteRequest
*/
func (a *SocialAPIService) ApiMatchesMatchIdFavoriteDelete(ctx context.Context, matchId string) SocialAPIApiMatchesMatchIdFavoriteDeleteRequest {
	return SocialAPIApiMatchesMatchIdFavoriteDeleteRequest{
		ApiService: a,
		ctx: ctx,
		matchId: matchId,
	}
}

// Execute executes the request
func (a *SocialAPIService) ApiMatchesMatchIdFavoriteDeleteExecute(r SocialAPIApiMatchesMatchIdFavoriteDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SocialAPIService.ApiMatchesMatchIdFavoriteDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/matches/{matchId}/favorite"
	localVarPath = strings.Replace(localVarPath, "{"+"matchId"+"}", url.PathEscape(parameterValueToString(r.matchId, "matchId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiMatchesMatchIdVerifyGet404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SocialAPIApiMatchesMatchIdFavoritePostRequest struct {
	ctx context.Context
	ApiService *SocialAPIService
	matchId string
}

func (r SocialAPIApiMatchesMatchIdFavoritePostRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApiMatchesMatchIdFavoritePostExecute(r)
}

/*
ApiMatchesMatchIdFavoritePost Favorite a match

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param matchId
 @return SocialAPIApiMatchesMatchIdFavoritePostRequest
*/
func (a *SocialAPIService) ApiMatchesMatchIdFavoritePost(ctx context.Context, matchId string) SocialAPIApiMatchesMatchIdFavoritePostRequest {
	return SocialAPIApiMatchesMatchIdFavoritePostRequest{
		ApiService: a,
		ctx: ctx,
		matchId: matchId,
	}
}

// Execute executes the request
func (a *SocialAPIService) ApiMatchesMatchIdFavoritePostExecute(r SocialAPIApiMatchesMatchIdFavoritePostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SocialAPIService.ApiMatchesMatchIdFavoritePost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/matches/{matchId}/favorite"
	localVarPath = strings.Replace(localVarPath, "{"+"matchId"+"}", url.PathEscape(parameterValueToString(r.matchId, "matchId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiMatchesMatchIdVerifyGet404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SocialAPIApiMatchesMatchIdRatePostRequest struct {
	ctx context.Context
	ApiService *SocialAPIService
	matchId string
	apiMatchesMatchIdRatePostRequest *ApiMatchesMatchIdRatePostRequest
}

func (r SocialAPIApiMatchesMatchIdRatePostRequest) ApiMatchesMatchIdRatePostRequest(apiMatchesMatchIdRatePostRequest ApiMatchesMatchIdRatePostRequest) SocialAPIApiMatchesMatchIdRatePostRequest {
	r.apiMatchesMatchIdRatePostRequest = &apiMatchesMatchIdRatePostRequest
	return r
}

func (r SocialAPIApiMatchesMatchIdRatePostRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApiMatchesMatchIdRatePostExecute(r)
}

/*
ApiMatchesMatchIdRatePost Rate a match

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param matchId
 @return SocialAPIApiMatchesMatchIdRatePostRequest
*/
func (a *SocialAPIService) ApiMatchesMatchIdRatePost(ctx context.Context, matchId string) SocialAPIApiMatchesMatchIdRatePostRequest {
	return SocialAPIApiMatchesMatchIdRatePostRequest{
		ApiService: a,
		ctx: ctx,
		matchId: matchId,
	}
}

// Execute executes the request
func (a *SocialAPIService) ApiMatchesMatchIdRatePostExecute(r SocialAPIApiMatchesMatchIdRatePostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SocialAPIService.ApiMatchesMatchIdRatePost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/matches/{matchId}/rate"
	localVarPath = strings.Replace(localVarPath, "{"+"matchId"+"}", url.PathEscape(parameterValueToString(r.matchId, "matchId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiMatchesMatchIdRatePostRequest == nil {
		return nil, reportError("apiMatchesMatchIdRatePostRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiMatchesMatchIdRatePostRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiMatchesMatchIdVerifyGet404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SocialAPIApiMatchesMatchIdSocialStatsGetRequest struct {
	ctx context.Context
	ApiService *SocialAPIService
	matchId string
}

func (r SocialAPIApiMatchesMatchIdSocialStatsGetRequest) Execute() (*ApiMatchesMatchIdSocialStatsGet200Response, *http.Response, error) {
	return r.ApiService.ApiMatchesMatchIdSocialStatsGetExecute(r)
}

/*
ApiMatchesMatchIdSocialStatsGet Get social stats for a match

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param matchId
 @return SocialAPIApiMatchesMatchIdSocialStatsGetRequest
*/
func (a *SocialAPIService) ApiMatchesMatchIdSocialStatsGet(ctx context.Context, matchId string) SocialAPIApiMatchesMatchIdSocialStatsGetRequest {
	return SocialAPIApiMatchesMatchIdSocialStatsGetRequest{
		ApiService: a,
		ctx: ctx,
		matchId: matchId,
	}
}

// Execute executes the request
//  @return ApiMatchesMatchIdSocialStatsGet200Response
func (a *SocialAPIService) ApiMatchesMatchIdSocialStatsGetExecute(r SocialAPIApiMatchesMatchIdSocialStatsGetRequest) (*ApiMatchesMatchIdSocialStatsGet200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiMatchesMatchIdSocialStatsGet200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SocialAPIService.ApiMatchesMatchIdSocialStatsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/matches/{matchId}/social-stats"
	localVarPath = strings.Replace(localVarPath, "{"+"matchId"+"}", url.PathEscape(parameterValueToString(r.matchId, "matchId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SocialAPIApiUsersTargetUserIdFollowDeleteRequest struct {
	ctx context.Context
	ApiService *SocialAPIService
	targetUserId string
}

func (r SocialAPIApiUsersTargetUserIdFollowDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApiUsersTargetUserIdFollowDeleteExecute(r)
}

/*
ApiUsersTargetUserIdFollowDelete Unfollow a user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param targetUserId
 @return SocialAPIApiUsersTargetUserIdFollowDeleteRequest
*/
func (a *SocialAPIService) ApiUsersTargetUserIdFollowDelete(ctx context.Context, targetUserId string) SocialAPIApiUsersTargetUserIdFollowDeleteRequest {
	return SocialAPIApiUsersTargetUserIdFollowDeleteRequest{
		ApiService: a,
		ctx: ctx,
		targetUserId: targetUserId,
	}
}

// Execute executes the request
func (a *SocialAPIService) ApiUsersTargetUserIdFollowDeleteExecute(r SocialAPIApiUsersTargetUserIdFollowDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SocialAPIService.ApiUsersTargetUserIdFollowDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/users/{targetUserId}/follow"
	localVarPath = strings.Replace(localVarPath, "{"+"targetUserId"+"}", url.PathEscape(parameterValueToString(r.targetUserId, "targetUserId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiMatchesMatchIdVerifyGet404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SocialAPIApiUsersTargetUserIdFollowPostRequest struct {
	ctx context.Context
	ApiService *SocialAPIService
	targetUserId string
}

func (r SocialAPIApiUsersTargetUserIdFollowPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApiUsersTargetUserIdFollowPostExecute(r)
}

/*
ApiUsersTargetUserIdFollowPost Follow a user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param targetUserId
 @return SocialAPIApiUsersTargetUserIdFollowPostRequest
*/
func (a *SocialAPIService) ApiUsersTargetUserIdFollowPost(ctx context.Context, targetUserId string) SocialAPIApiUsersTargetUserIdFollowPostRequest {
	return SocialAPIApiUsersTargetUserIdFollowPostRequest{
		ApiService: a,
		ctx: ctx,
		targetUserId: targetUserId,
	}
}

// Execute executes the request
func (a *SocialAPIService) ApiUsersTargetUserIdFollowPostExecute(r SocialAPIApiUsersTargetUserIdFollowPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SocialAPIService.ApiUsersTargetUserIdFollowPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/users/{targetUserId}/follow"
	localVarPath = strings.Replace(localVarPath, "{"+"targetUserId"+"}", url.PathEscape(parameterValueToString(r.targetUserId, "targetUserId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ApiMatchesMatchIdVerifyGet404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ApiMatchesMatchIdVerifyGet404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SocialAPIApiUsersUserIdFavoritesGetRequest struct {
	ctx context.Context
	ApiService *SocialAPIService
	userId string
}

func (r SocialAPIApiUsersUserIdFavoritesGetRequest) Execute() ([]ApiUsersUserIdFavoritesGet200ResponseInner, *http.Response, error) {
	return r.ApiService.ApiUsersUserIdFavoritesGetExecute(r)
}

/*
ApiUsersUserIdFavoritesGet Get favorite matches for a user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param userId
 @return SocialAPIApiUsersUserIdFavoritesGetRequest
*/
func (a *SocialAPIService) ApiUsersUserIdFavoritesGet(ctx context.Context, userId string) SocialAPIApiUsersUserIdFavoritesGetRequest {
	return SocialAPIApiUsersUserIdFavoritesGetRequest{
		ApiService: a,
		ctx: ctx,
		userId: userId,
	}
}

// Execute executes the request
//  @return []ApiUsersUserIdFavoritesGet200ResponseInner
func (a *SocialAPIService) ApiUsersUserIdFavoritesGetExecute(r SocialAPIApiUsersUserIdFavoritesGetRequest) ([]ApiUsersUserIdFavoritesGet200ResponseInner, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []ApiUsersUserIdFavoritesGet200ResponseInner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SocialAPIService.ApiUsersUserIdFavoritesGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/users/{userId}/favorites"
	localVarPath = strings.Replace(localVarPath, "{"+"userId"+"}", url.PathEscape(parameterValueToString(r.userId, "userId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SocialAPIApiUsersUserIdFollowStatsGetRequest struct {
	ctx context.Context
	ApiService *SocialAPIService
	userId string
}

func (r SocialAPIApiUsersUserIdFollowStatsGetRequest) Execute() (*ApiUsersUserIdFollowStatsGet200Response, *http.Response, error) {
	return r.ApiService.ApiUsersUserIdFollowStatsGetExecute(r)
}

/*
ApiUsersUserIdFollowStatsGet Get follow stats for a user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param userId
 @return SocialAPIApiUsersUserIdFollowStatsGetRequest
*/
func (a *SocialAPIService) ApiUsersUserIdFollowStatsGet(ctx context.Context, userId string) SocialAPIApiUsersUserIdFollowStatsGetRequest {
	return SocialAPIApiUsersUserIdFollowStatsGetRequest{
		ApiService: a,
		ctx: ctx,
		userId: userId,
	}
}

// Execute executes the request
//  @return ApiUsersUserIdFollowStatsGet200Response
func (a *SocialAPIService) ApiUsersUserIdFollowStatsGetExecute(r SocialAPIApiUsersUserIdFollowStatsGetRequest) (*ApiUsersUserIdFollowStatsGet200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiUsersUserIdFollowStatsGet200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SocialAPIService.ApiUsersUserIdFollowStatsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/users/{userId}/follow-stats"
	localVarPath = strings.Replace(localVarPath, "{"+"userId"+"}", url.PathEscape(parameterValueToString(r.userId, "userId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ApiMatchesMatchIdVerifyGet404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
