/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MatchesIdLogGet200ResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MatchesIdLogGet200ResponseOneOf{}

// MatchesIdLogGet200ResponseOneOf struct for MatchesIdLogGet200ResponseOneOf
type MatchesIdLogGet200ResponseOneOf struct {
	MatchId string `json:"matchId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	Events []MatchesIdLogGet200ResponseOneOfEventsInner `json:"events"`
	Fingerprint string `json:"fingerprint"`
	GeneratedAt time.Time `json:"generatedAt" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
}

type _MatchesIdLogGet200ResponseOneOf MatchesIdLogGet200ResponseOneOf

// NewMatchesIdLogGet200ResponseOneOf instantiates a new MatchesIdLogGet200ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatchesIdLogGet200ResponseOneOf(matchId string, events []MatchesIdLogGet200ResponseOneOfEventsInner, fingerprint string, generatedAt time.Time) *MatchesIdLogGet200ResponseOneOf {
	this := MatchesIdLogGet200ResponseOneOf{}
	this.MatchId = matchId
	this.Events = events
	this.Fingerprint = fingerprint
	this.GeneratedAt = generatedAt
	return &this
}

// NewMatchesIdLogGet200ResponseOneOfWithDefaults instantiates a new MatchesIdLogGet200ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatchesIdLogGet200ResponseOneOfWithDefaults() *MatchesIdLogGet200ResponseOneOf {
	this := MatchesIdLogGet200ResponseOneOf{}
	return &this
}

// GetMatchId returns the MatchId field value
func (o *MatchesIdLogGet200ResponseOneOf) GetMatchId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MatchId
}

// GetMatchIdOk returns a tuple with the MatchId field value
// and a boolean to check if the value has been set.
func (o *MatchesIdLogGet200ResponseOneOf) GetMatchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MatchId, true
}

// SetMatchId sets field value
func (o *MatchesIdLogGet200ResponseOneOf) SetMatchId(v string) {
	o.MatchId = v
}

// GetEvents returns the Events field value
func (o *MatchesIdLogGet200ResponseOneOf) GetEvents() []MatchesIdLogGet200ResponseOneOfEventsInner {
	if o == nil {
		var ret []MatchesIdLogGet200ResponseOneOfEventsInner
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *MatchesIdLogGet200ResponseOneOf) GetEventsOk() ([]MatchesIdLogGet200ResponseOneOfEventsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *MatchesIdLogGet200ResponseOneOf) SetEvents(v []MatchesIdLogGet200ResponseOneOfEventsInner) {
	o.Events = v
}

// GetFingerprint returns the Fingerprint field value
func (o *MatchesIdLogGet200ResponseOneOf) GetFingerprint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fingerprint
}

// GetFingerprintOk returns a tuple with the Fingerprint field value
// and a boolean to check if the value has been set.
func (o *MatchesIdLogGet200ResponseOneOf) GetFingerprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fingerprint, true
}

// SetFingerprint sets field value
func (o *MatchesIdLogGet200ResponseOneOf) SetFingerprint(v string) {
	o.Fingerprint = v
}

// GetGeneratedAt returns the GeneratedAt field value
func (o *MatchesIdLogGet200ResponseOneOf) GetGeneratedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.GeneratedAt
}

// GetGeneratedAtOk returns a tuple with the GeneratedAt field value
// and a boolean to check if the value has been set.
func (o *MatchesIdLogGet200ResponseOneOf) GetGeneratedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GeneratedAt, true
}

// SetGeneratedAt sets field value
func (o *MatchesIdLogGet200ResponseOneOf) SetGeneratedAt(v time.Time) {
	o.GeneratedAt = v
}

func (o MatchesIdLogGet200ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MatchesIdLogGet200ResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["matchId"] = o.MatchId
	toSerialize["events"] = o.Events
	toSerialize["fingerprint"] = o.Fingerprint
	toSerialize["generatedAt"] = o.GeneratedAt
	return toSerialize, nil
}

func (o *MatchesIdLogGet200ResponseOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"matchId",
		"events",
		"fingerprint",
		"generatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMatchesIdLogGet200ResponseOneOf := _MatchesIdLogGet200ResponseOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMatchesIdLogGet200ResponseOneOf)

	if err != nil {
		return err
	}

	*o = MatchesIdLogGet200ResponseOneOf(varMatchesIdLogGet200ResponseOneOf)

	return err
}

type NullableMatchesIdLogGet200ResponseOneOf struct {
	value *MatchesIdLogGet200ResponseOneOf
	isSet bool
}

func (v NullableMatchesIdLogGet200ResponseOneOf) Get() *MatchesIdLogGet200ResponseOneOf {
	return v.value
}

func (v *NullableMatchesIdLogGet200ResponseOneOf) Set(val *MatchesIdLogGet200ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableMatchesIdLogGet200ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableMatchesIdLogGet200ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatchesIdLogGet200ResponseOneOf(val *MatchesIdLogGet200ResponseOneOf) *NullableMatchesIdLogGet200ResponseOneOf {
	return &NullableMatchesIdLogGet200ResponseOneOf{value: val, isSet: true}
}

func (v NullableMatchesIdLogGet200ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatchesIdLogGet200ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


