/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
)

// checks if the ApiDefaultsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDefaultsGet200Response{}

// ApiDefaultsGet200Response Default match parameters and metadata
type ApiDefaultsGet200Response struct {
	SpecVersion *string `json:"specVersion,omitempty"`
	Rows *int32 `json:"rows,omitempty"`
	Columns *int32 `json:"columns,omitempty"`
	MaxHandSize *int32 `json:"maxHandSize,omitempty"`
	InitialDraw *int32 `json:"initialDraw,omitempty"`
	ModeClassicAces *bool `json:"modeClassicAces,omitempty"`
	ModeClassicFaceCards *bool `json:"modeClassicFaceCards,omitempty"`
	ModeDamagePersistence *string `json:"modeDamagePersistence,omitempty"`
	ModeClassicDeployment *bool `json:"modeClassicDeployment,omitempty"`
	ModeQuickStart *bool `json:"modeQuickStart,omitempty"`
	StartingLifepoints *int32 `json:"startingLifepoints,omitempty"`
	Initiative *ApiDefaultsGet200ResponseInitiative `json:"initiative,omitempty"`
	Meta *ApiDefaultsGet200ResponseMeta `json:"_meta,omitempty"`
}

// NewApiDefaultsGet200Response instantiates a new ApiDefaultsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDefaultsGet200Response() *ApiDefaultsGet200Response {
	this := ApiDefaultsGet200Response{}
	return &this
}

// NewApiDefaultsGet200ResponseWithDefaults instantiates a new ApiDefaultsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDefaultsGet200ResponseWithDefaults() *ApiDefaultsGet200Response {
	this := ApiDefaultsGet200Response{}
	return &this
}

// GetSpecVersion returns the SpecVersion field value if set, zero value otherwise.
func (o *ApiDefaultsGet200Response) GetSpecVersion() string {
	if o == nil || IsNil(o.SpecVersion) {
		var ret string
		return ret
	}
	return *o.SpecVersion
}

// GetSpecVersionOk returns a tuple with the SpecVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200Response) GetSpecVersionOk() (*string, bool) {
	if o == nil || IsNil(o.SpecVersion) {
		return nil, false
	}
	return o.SpecVersion, true
}

// HasSpecVersion returns a boolean if a field has been set.
func (o *ApiDefaultsGet200Response) HasSpecVersion() bool {
	if o != nil && !IsNil(o.SpecVersion) {
		return true
	}

	return false
}

// SetSpecVersion gets a reference to the given string and assigns it to the SpecVersion field.
func (o *ApiDefaultsGet200Response) SetSpecVersion(v string) {
	o.SpecVersion = &v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *ApiDefaultsGet200Response) GetRows() int32 {
	if o == nil || IsNil(o.Rows) {
		var ret int32
		return ret
	}
	return *o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200Response) GetRowsOk() (*int32, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *ApiDefaultsGet200Response) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given int32 and assigns it to the Rows field.
func (o *ApiDefaultsGet200Response) SetRows(v int32) {
	o.Rows = &v
}

// GetColumns returns the Columns field value if set, zero value otherwise.
func (o *ApiDefaultsGet200Response) GetColumns() int32 {
	if o == nil || IsNil(o.Columns) {
		var ret int32
		return ret
	}
	return *o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200Response) GetColumnsOk() (*int32, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *ApiDefaultsGet200Response) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given int32 and assigns it to the Columns field.
func (o *ApiDefaultsGet200Response) SetColumns(v int32) {
	o.Columns = &v
}

// GetMaxHandSize returns the MaxHandSize field value if set, zero value otherwise.
func (o *ApiDefaultsGet200Response) GetMaxHandSize() int32 {
	if o == nil || IsNil(o.MaxHandSize) {
		var ret int32
		return ret
	}
	return *o.MaxHandSize
}

// GetMaxHandSizeOk returns a tuple with the MaxHandSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200Response) GetMaxHandSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxHandSize) {
		return nil, false
	}
	return o.MaxHandSize, true
}

// HasMaxHandSize returns a boolean if a field has been set.
func (o *ApiDefaultsGet200Response) HasMaxHandSize() bool {
	if o != nil && !IsNil(o.MaxHandSize) {
		return true
	}

	return false
}

// SetMaxHandSize gets a reference to the given int32 and assigns it to the MaxHandSize field.
func (o *ApiDefaultsGet200Response) SetMaxHandSize(v int32) {
	o.MaxHandSize = &v
}

// GetInitialDraw returns the InitialDraw field value if set, zero value otherwise.
func (o *ApiDefaultsGet200Response) GetInitialDraw() int32 {
	if o == nil || IsNil(o.InitialDraw) {
		var ret int32
		return ret
	}
	return *o.InitialDraw
}

// GetInitialDrawOk returns a tuple with the InitialDraw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200Response) GetInitialDrawOk() (*int32, bool) {
	if o == nil || IsNil(o.InitialDraw) {
		return nil, false
	}
	return o.InitialDraw, true
}

// HasInitialDraw returns a boolean if a field has been set.
func (o *ApiDefaultsGet200Response) HasInitialDraw() bool {
	if o != nil && !IsNil(o.InitialDraw) {
		return true
	}

	return false
}

// SetInitialDraw gets a reference to the given int32 and assigns it to the InitialDraw field.
func (o *ApiDefaultsGet200Response) SetInitialDraw(v int32) {
	o.InitialDraw = &v
}

// GetModeClassicAces returns the ModeClassicAces field value if set, zero value otherwise.
func (o *ApiDefaultsGet200Response) GetModeClassicAces() bool {
	if o == nil || IsNil(o.ModeClassicAces) {
		var ret bool
		return ret
	}
	return *o.ModeClassicAces
}

// GetModeClassicAcesOk returns a tuple with the ModeClassicAces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200Response) GetModeClassicAcesOk() (*bool, bool) {
	if o == nil || IsNil(o.ModeClassicAces) {
		return nil, false
	}
	return o.ModeClassicAces, true
}

// HasModeClassicAces returns a boolean if a field has been set.
func (o *ApiDefaultsGet200Response) HasModeClassicAces() bool {
	if o != nil && !IsNil(o.ModeClassicAces) {
		return true
	}

	return false
}

// SetModeClassicAces gets a reference to the given bool and assigns it to the ModeClassicAces field.
func (o *ApiDefaultsGet200Response) SetModeClassicAces(v bool) {
	o.ModeClassicAces = &v
}

// GetModeClassicFaceCards returns the ModeClassicFaceCards field value if set, zero value otherwise.
func (o *ApiDefaultsGet200Response) GetModeClassicFaceCards() bool {
	if o == nil || IsNil(o.ModeClassicFaceCards) {
		var ret bool
		return ret
	}
	return *o.ModeClassicFaceCards
}

// GetModeClassicFaceCardsOk returns a tuple with the ModeClassicFaceCards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200Response) GetModeClassicFaceCardsOk() (*bool, bool) {
	if o == nil || IsNil(o.ModeClassicFaceCards) {
		return nil, false
	}
	return o.ModeClassicFaceCards, true
}

// HasModeClassicFaceCards returns a boolean if a field has been set.
func (o *ApiDefaultsGet200Response) HasModeClassicFaceCards() bool {
	if o != nil && !IsNil(o.ModeClassicFaceCards) {
		return true
	}

	return false
}

// SetModeClassicFaceCards gets a reference to the given bool and assigns it to the ModeClassicFaceCards field.
func (o *ApiDefaultsGet200Response) SetModeClassicFaceCards(v bool) {
	o.ModeClassicFaceCards = &v
}

// GetModeDamagePersistence returns the ModeDamagePersistence field value if set, zero value otherwise.
func (o *ApiDefaultsGet200Response) GetModeDamagePersistence() string {
	if o == nil || IsNil(o.ModeDamagePersistence) {
		var ret string
		return ret
	}
	return *o.ModeDamagePersistence
}

// GetModeDamagePersistenceOk returns a tuple with the ModeDamagePersistence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200Response) GetModeDamagePersistenceOk() (*string, bool) {
	if o == nil || IsNil(o.ModeDamagePersistence) {
		return nil, false
	}
	return o.ModeDamagePersistence, true
}

// HasModeDamagePersistence returns a boolean if a field has been set.
func (o *ApiDefaultsGet200Response) HasModeDamagePersistence() bool {
	if o != nil && !IsNil(o.ModeDamagePersistence) {
		return true
	}

	return false
}

// SetModeDamagePersistence gets a reference to the given string and assigns it to the ModeDamagePersistence field.
func (o *ApiDefaultsGet200Response) SetModeDamagePersistence(v string) {
	o.ModeDamagePersistence = &v
}

// GetModeClassicDeployment returns the ModeClassicDeployment field value if set, zero value otherwise.
func (o *ApiDefaultsGet200Response) GetModeClassicDeployment() bool {
	if o == nil || IsNil(o.ModeClassicDeployment) {
		var ret bool
		return ret
	}
	return *o.ModeClassicDeployment
}

// GetModeClassicDeploymentOk returns a tuple with the ModeClassicDeployment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200Response) GetModeClassicDeploymentOk() (*bool, bool) {
	if o == nil || IsNil(o.ModeClassicDeployment) {
		return nil, false
	}
	return o.ModeClassicDeployment, true
}

// HasModeClassicDeployment returns a boolean if a field has been set.
func (o *ApiDefaultsGet200Response) HasModeClassicDeployment() bool {
	if o != nil && !IsNil(o.ModeClassicDeployment) {
		return true
	}

	return false
}

// SetModeClassicDeployment gets a reference to the given bool and assigns it to the ModeClassicDeployment field.
func (o *ApiDefaultsGet200Response) SetModeClassicDeployment(v bool) {
	o.ModeClassicDeployment = &v
}

// GetModeQuickStart returns the ModeQuickStart field value if set, zero value otherwise.
func (o *ApiDefaultsGet200Response) GetModeQuickStart() bool {
	if o == nil || IsNil(o.ModeQuickStart) {
		var ret bool
		return ret
	}
	return *o.ModeQuickStart
}

// GetModeQuickStartOk returns a tuple with the ModeQuickStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200Response) GetModeQuickStartOk() (*bool, bool) {
	if o == nil || IsNil(o.ModeQuickStart) {
		return nil, false
	}
	return o.ModeQuickStart, true
}

// HasModeQuickStart returns a boolean if a field has been set.
func (o *ApiDefaultsGet200Response) HasModeQuickStart() bool {
	if o != nil && !IsNil(o.ModeQuickStart) {
		return true
	}

	return false
}

// SetModeQuickStart gets a reference to the given bool and assigns it to the ModeQuickStart field.
func (o *ApiDefaultsGet200Response) SetModeQuickStart(v bool) {
	o.ModeQuickStart = &v
}

// GetStartingLifepoints returns the StartingLifepoints field value if set, zero value otherwise.
func (o *ApiDefaultsGet200Response) GetStartingLifepoints() int32 {
	if o == nil || IsNil(o.StartingLifepoints) {
		var ret int32
		return ret
	}
	return *o.StartingLifepoints
}

// GetStartingLifepointsOk returns a tuple with the StartingLifepoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200Response) GetStartingLifepointsOk() (*int32, bool) {
	if o == nil || IsNil(o.StartingLifepoints) {
		return nil, false
	}
	return o.StartingLifepoints, true
}

// HasStartingLifepoints returns a boolean if a field has been set.
func (o *ApiDefaultsGet200Response) HasStartingLifepoints() bool {
	if o != nil && !IsNil(o.StartingLifepoints) {
		return true
	}

	return false
}

// SetStartingLifepoints gets a reference to the given int32 and assigns it to the StartingLifepoints field.
func (o *ApiDefaultsGet200Response) SetStartingLifepoints(v int32) {
	o.StartingLifepoints = &v
}

// GetInitiative returns the Initiative field value if set, zero value otherwise.
func (o *ApiDefaultsGet200Response) GetInitiative() ApiDefaultsGet200ResponseInitiative {
	if o == nil || IsNil(o.Initiative) {
		var ret ApiDefaultsGet200ResponseInitiative
		return ret
	}
	return *o.Initiative
}

// GetInitiativeOk returns a tuple with the Initiative field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200Response) GetInitiativeOk() (*ApiDefaultsGet200ResponseInitiative, bool) {
	if o == nil || IsNil(o.Initiative) {
		return nil, false
	}
	return o.Initiative, true
}

// HasInitiative returns a boolean if a field has been set.
func (o *ApiDefaultsGet200Response) HasInitiative() bool {
	if o != nil && !IsNil(o.Initiative) {
		return true
	}

	return false
}

// SetInitiative gets a reference to the given ApiDefaultsGet200ResponseInitiative and assigns it to the Initiative field.
func (o *ApiDefaultsGet200Response) SetInitiative(v ApiDefaultsGet200ResponseInitiative) {
	o.Initiative = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ApiDefaultsGet200Response) GetMeta() ApiDefaultsGet200ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret ApiDefaultsGet200ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200Response) GetMetaOk() (*ApiDefaultsGet200ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ApiDefaultsGet200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ApiDefaultsGet200ResponseMeta and assigns it to the Meta field.
func (o *ApiDefaultsGet200Response) SetMeta(v ApiDefaultsGet200ResponseMeta) {
	o.Meta = &v
}

func (o ApiDefaultsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDefaultsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SpecVersion) {
		toSerialize["specVersion"] = o.SpecVersion
	}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	if !IsNil(o.Columns) {
		toSerialize["columns"] = o.Columns
	}
	if !IsNil(o.MaxHandSize) {
		toSerialize["maxHandSize"] = o.MaxHandSize
	}
	if !IsNil(o.InitialDraw) {
		toSerialize["initialDraw"] = o.InitialDraw
	}
	if !IsNil(o.ModeClassicAces) {
		toSerialize["modeClassicAces"] = o.ModeClassicAces
	}
	if !IsNil(o.ModeClassicFaceCards) {
		toSerialize["modeClassicFaceCards"] = o.ModeClassicFaceCards
	}
	if !IsNil(o.ModeDamagePersistence) {
		toSerialize["modeDamagePersistence"] = o.ModeDamagePersistence
	}
	if !IsNil(o.ModeClassicDeployment) {
		toSerialize["modeClassicDeployment"] = o.ModeClassicDeployment
	}
	if !IsNil(o.ModeQuickStart) {
		toSerialize["modeQuickStart"] = o.ModeQuickStart
	}
	if !IsNil(o.StartingLifepoints) {
		toSerialize["startingLifepoints"] = o.StartingLifepoints
	}
	if !IsNil(o.Initiative) {
		toSerialize["initiative"] = o.Initiative
	}
	if !IsNil(o.Meta) {
		toSerialize["_meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableApiDefaultsGet200Response struct {
	value *ApiDefaultsGet200Response
	isSet bool
}

func (v NullableApiDefaultsGet200Response) Get() *ApiDefaultsGet200Response {
	return v.value
}

func (v *NullableApiDefaultsGet200Response) Set(val *ApiDefaultsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDefaultsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDefaultsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDefaultsGet200Response(val *ApiDefaultsGet200Response) *NullableApiDefaultsGet200Response {
	return &NullableApiDefaultsGet200Response{value: val, isSet: true}
}

func (v NullableApiDefaultsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDefaultsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


