/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiMatchesIdReplayGet200ResponseParamsClassicModes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMatchesIdReplayGet200ResponseParamsClassicModes{}

// ApiMatchesIdReplayGet200ResponseParamsClassicModes struct for ApiMatchesIdReplayGet200ResponseParamsClassicModes
type ApiMatchesIdReplayGet200ResponseParamsClassicModes struct {
	// Enable Classic Ace rules: Aces only destroyed by other Aces at rank 0 (§10).
	ClassicAces bool `json:"classicAces"`
	// Enable Classic Face Card rules: J→J, Q→J/Q, K→J/Q/K destruction hierarchy (§11).
	ClassicFaceCards bool `json:"classicFaceCards"`
	// Damage mode. classic: no HP persists between turns. cumulative: damage persists (§12).
	DamagePersistence string `json:"damagePersistence"`
	// Reserved compatibility flag. Must be false for v2.0-compliant matches (§3.4).
	QuickStart bool `json:"quickStart"`
}

type _ApiMatchesIdReplayGet200ResponseParamsClassicModes ApiMatchesIdReplayGet200ResponseParamsClassicModes

// NewApiMatchesIdReplayGet200ResponseParamsClassicModes instantiates a new ApiMatchesIdReplayGet200ResponseParamsClassicModes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMatchesIdReplayGet200ResponseParamsClassicModes(classicAces bool, classicFaceCards bool, damagePersistence string, quickStart bool) *ApiMatchesIdReplayGet200ResponseParamsClassicModes {
	this := ApiMatchesIdReplayGet200ResponseParamsClassicModes{}
	this.ClassicAces = classicAces
	this.ClassicFaceCards = classicFaceCards
	this.DamagePersistence = damagePersistence
	this.QuickStart = quickStart
	return &this
}

// NewApiMatchesIdReplayGet200ResponseParamsClassicModesWithDefaults instantiates a new ApiMatchesIdReplayGet200ResponseParamsClassicModes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMatchesIdReplayGet200ResponseParamsClassicModesWithDefaults() *ApiMatchesIdReplayGet200ResponseParamsClassicModes {
	this := ApiMatchesIdReplayGet200ResponseParamsClassicModes{}
	var classicAces bool = true
	this.ClassicAces = classicAces
	var classicFaceCards bool = true
	this.ClassicFaceCards = classicFaceCards
	var damagePersistence string = "classic"
	this.DamagePersistence = damagePersistence
	var quickStart bool = false
	this.QuickStart = quickStart
	return &this
}

// GetClassicAces returns the ClassicAces field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicModes) GetClassicAces() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ClassicAces
}

// GetClassicAcesOk returns a tuple with the ClassicAces field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicModes) GetClassicAcesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassicAces, true
}

// SetClassicAces sets field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicModes) SetClassicAces(v bool) {
	o.ClassicAces = v
}

// GetClassicFaceCards returns the ClassicFaceCards field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicModes) GetClassicFaceCards() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ClassicFaceCards
}

// GetClassicFaceCardsOk returns a tuple with the ClassicFaceCards field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicModes) GetClassicFaceCardsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassicFaceCards, true
}

// SetClassicFaceCards sets field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicModes) SetClassicFaceCards(v bool) {
	o.ClassicFaceCards = v
}

// GetDamagePersistence returns the DamagePersistence field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicModes) GetDamagePersistence() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DamagePersistence
}

// GetDamagePersistenceOk returns a tuple with the DamagePersistence field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicModes) GetDamagePersistenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DamagePersistence, true
}

// SetDamagePersistence sets field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicModes) SetDamagePersistence(v string) {
	o.DamagePersistence = v
}

// GetQuickStart returns the QuickStart field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicModes) GetQuickStart() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.QuickStart
}

// GetQuickStartOk returns a tuple with the QuickStart field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicModes) GetQuickStartOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuickStart, true
}

// SetQuickStart sets field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicModes) SetQuickStart(v bool) {
	o.QuickStart = v
}

func (o ApiMatchesIdReplayGet200ResponseParamsClassicModes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMatchesIdReplayGet200ResponseParamsClassicModes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["classicAces"] = o.ClassicAces
	toSerialize["classicFaceCards"] = o.ClassicFaceCards
	toSerialize["damagePersistence"] = o.DamagePersistence
	toSerialize["quickStart"] = o.QuickStart
	return toSerialize, nil
}

func (o *ApiMatchesIdReplayGet200ResponseParamsClassicModes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"classicAces",
		"classicFaceCards",
		"damagePersistence",
		"quickStart",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiMatchesIdReplayGet200ResponseParamsClassicModes := _ApiMatchesIdReplayGet200ResponseParamsClassicModes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiMatchesIdReplayGet200ResponseParamsClassicModes)

	if err != nil {
		return err
	}

	*o = ApiMatchesIdReplayGet200ResponseParamsClassicModes(varApiMatchesIdReplayGet200ResponseParamsClassicModes)

	return err
}

type NullableApiMatchesIdReplayGet200ResponseParamsClassicModes struct {
	value *ApiMatchesIdReplayGet200ResponseParamsClassicModes
	isSet bool
}

func (v NullableApiMatchesIdReplayGet200ResponseParamsClassicModes) Get() *ApiMatchesIdReplayGet200ResponseParamsClassicModes {
	return v.value
}

func (v *NullableApiMatchesIdReplayGet200ResponseParamsClassicModes) Set(val *ApiMatchesIdReplayGet200ResponseParamsClassicModes) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMatchesIdReplayGet200ResponseParamsClassicModes) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMatchesIdReplayGet200ResponseParamsClassicModes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMatchesIdReplayGet200ResponseParamsClassicModes(val *ApiMatchesIdReplayGet200ResponseParamsClassicModes) *NullableApiMatchesIdReplayGet200ResponseParamsClassicModes {
	return &NullableApiMatchesIdReplayGet200ResponseParamsClassicModes{value: val, isSet: true}
}

func (v NullableApiMatchesIdReplayGet200ResponseParamsClassicModes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMatchesIdReplayGet200ResponseParamsClassicModes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


