/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ApiMatchesActiveGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMatchesActiveGet200ResponseInner{}

// ApiMatchesActiveGet200ResponseInner struct for ApiMatchesActiveGet200ResponseInner
type ApiMatchesActiveGet200ResponseInner struct {
	MatchId string `json:"matchId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	PlayerId string `json:"playerId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	PlayerIndex int32 `json:"playerIndex"`
	Role string `json:"role"`
	OpponentName NullableString `json:"opponentName"`
	BotStrategy NullableString `json:"botStrategy"`
	Status string `json:"status"`
	Phase NullableString `json:"phase"`
	TurnNumber NullableInt32 `json:"turnNumber"`
	Disconnected bool `json:"disconnected"`
	CreatedAt time.Time `json:"createdAt" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	UpdatedAt time.Time `json:"updatedAt" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
}

type _ApiMatchesActiveGet200ResponseInner ApiMatchesActiveGet200ResponseInner

// NewApiMatchesActiveGet200ResponseInner instantiates a new ApiMatchesActiveGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMatchesActiveGet200ResponseInner(matchId string, playerId string, playerIndex int32, role string, opponentName NullableString, botStrategy NullableString, status string, phase NullableString, turnNumber NullableInt32, disconnected bool, createdAt time.Time, updatedAt time.Time) *ApiMatchesActiveGet200ResponseInner {
	this := ApiMatchesActiveGet200ResponseInner{}
	this.MatchId = matchId
	this.PlayerId = playerId
	this.PlayerIndex = playerIndex
	this.Role = role
	this.OpponentName = opponentName
	this.BotStrategy = botStrategy
	this.Status = status
	this.Phase = phase
	this.TurnNumber = turnNumber
	this.Disconnected = disconnected
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewApiMatchesActiveGet200ResponseInnerWithDefaults instantiates a new ApiMatchesActiveGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMatchesActiveGet200ResponseInnerWithDefaults() *ApiMatchesActiveGet200ResponseInner {
	this := ApiMatchesActiveGet200ResponseInner{}
	return &this
}

// GetMatchId returns the MatchId field value
func (o *ApiMatchesActiveGet200ResponseInner) GetMatchId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MatchId
}

// GetMatchIdOk returns a tuple with the MatchId field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesActiveGet200ResponseInner) GetMatchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MatchId, true
}

// SetMatchId sets field value
func (o *ApiMatchesActiveGet200ResponseInner) SetMatchId(v string) {
	o.MatchId = v
}

// GetPlayerId returns the PlayerId field value
func (o *ApiMatchesActiveGet200ResponseInner) GetPlayerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesActiveGet200ResponseInner) GetPlayerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlayerId, true
}

// SetPlayerId sets field value
func (o *ApiMatchesActiveGet200ResponseInner) SetPlayerId(v string) {
	o.PlayerId = v
}

// GetPlayerIndex returns the PlayerIndex field value
func (o *ApiMatchesActiveGet200ResponseInner) GetPlayerIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PlayerIndex
}

// GetPlayerIndexOk returns a tuple with the PlayerIndex field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesActiveGet200ResponseInner) GetPlayerIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlayerIndex, true
}

// SetPlayerIndex sets field value
func (o *ApiMatchesActiveGet200ResponseInner) SetPlayerIndex(v int32) {
	o.PlayerIndex = v
}

// GetRole returns the Role field value
func (o *ApiMatchesActiveGet200ResponseInner) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesActiveGet200ResponseInner) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ApiMatchesActiveGet200ResponseInner) SetRole(v string) {
	o.Role = v
}

// GetOpponentName returns the OpponentName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiMatchesActiveGet200ResponseInner) GetOpponentName() string {
	if o == nil || o.OpponentName.Get() == nil {
		var ret string
		return ret
	}

	return *o.OpponentName.Get()
}

// GetOpponentNameOk returns a tuple with the OpponentName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiMatchesActiveGet200ResponseInner) GetOpponentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OpponentName.Get(), o.OpponentName.IsSet()
}

// SetOpponentName sets field value
func (o *ApiMatchesActiveGet200ResponseInner) SetOpponentName(v string) {
	o.OpponentName.Set(&v)
}

// GetBotStrategy returns the BotStrategy field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiMatchesActiveGet200ResponseInner) GetBotStrategy() string {
	if o == nil || o.BotStrategy.Get() == nil {
		var ret string
		return ret
	}

	return *o.BotStrategy.Get()
}

// GetBotStrategyOk returns a tuple with the BotStrategy field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiMatchesActiveGet200ResponseInner) GetBotStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BotStrategy.Get(), o.BotStrategy.IsSet()
}

// SetBotStrategy sets field value
func (o *ApiMatchesActiveGet200ResponseInner) SetBotStrategy(v string) {
	o.BotStrategy.Set(&v)
}

// GetStatus returns the Status field value
func (o *ApiMatchesActiveGet200ResponseInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesActiveGet200ResponseInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ApiMatchesActiveGet200ResponseInner) SetStatus(v string) {
	o.Status = v
}

// GetPhase returns the Phase field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiMatchesActiveGet200ResponseInner) GetPhase() string {
	if o == nil || o.Phase.Get() == nil {
		var ret string
		return ret
	}

	return *o.Phase.Get()
}

// GetPhaseOk returns a tuple with the Phase field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiMatchesActiveGet200ResponseInner) GetPhaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Phase.Get(), o.Phase.IsSet()
}

// SetPhase sets field value
func (o *ApiMatchesActiveGet200ResponseInner) SetPhase(v string) {
	o.Phase.Set(&v)
}

// GetTurnNumber returns the TurnNumber field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ApiMatchesActiveGet200ResponseInner) GetTurnNumber() int32 {
	if o == nil || o.TurnNumber.Get() == nil {
		var ret int32
		return ret
	}

	return *o.TurnNumber.Get()
}

// GetTurnNumberOk returns a tuple with the TurnNumber field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiMatchesActiveGet200ResponseInner) GetTurnNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TurnNumber.Get(), o.TurnNumber.IsSet()
}

// SetTurnNumber sets field value
func (o *ApiMatchesActiveGet200ResponseInner) SetTurnNumber(v int32) {
	o.TurnNumber.Set(&v)
}

// GetDisconnected returns the Disconnected field value
func (o *ApiMatchesActiveGet200ResponseInner) GetDisconnected() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Disconnected
}

// GetDisconnectedOk returns a tuple with the Disconnected field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesActiveGet200ResponseInner) GetDisconnectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disconnected, true
}

// SetDisconnected sets field value
func (o *ApiMatchesActiveGet200ResponseInner) SetDisconnected(v bool) {
	o.Disconnected = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ApiMatchesActiveGet200ResponseInner) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesActiveGet200ResponseInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ApiMatchesActiveGet200ResponseInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ApiMatchesActiveGet200ResponseInner) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesActiveGet200ResponseInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ApiMatchesActiveGet200ResponseInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o ApiMatchesActiveGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMatchesActiveGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["matchId"] = o.MatchId
	toSerialize["playerId"] = o.PlayerId
	toSerialize["playerIndex"] = o.PlayerIndex
	toSerialize["role"] = o.Role
	toSerialize["opponentName"] = o.OpponentName.Get()
	toSerialize["botStrategy"] = o.BotStrategy.Get()
	toSerialize["status"] = o.Status
	toSerialize["phase"] = o.Phase.Get()
	toSerialize["turnNumber"] = o.TurnNumber.Get()
	toSerialize["disconnected"] = o.Disconnected
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *ApiMatchesActiveGet200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"matchId",
		"playerId",
		"playerIndex",
		"role",
		"opponentName",
		"botStrategy",
		"status",
		"phase",
		"turnNumber",
		"disconnected",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiMatchesActiveGet200ResponseInner := _ApiMatchesActiveGet200ResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiMatchesActiveGet200ResponseInner)

	if err != nil {
		return err
	}

	*o = ApiMatchesActiveGet200ResponseInner(varApiMatchesActiveGet200ResponseInner)

	return err
}

type NullableApiMatchesActiveGet200ResponseInner struct {
	value *ApiMatchesActiveGet200ResponseInner
	isSet bool
}

func (v NullableApiMatchesActiveGet200ResponseInner) Get() *ApiMatchesActiveGet200ResponseInner {
	return v.value
}

func (v *NullableApiMatchesActiveGet200ResponseInner) Set(val *ApiMatchesActiveGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMatchesActiveGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMatchesActiveGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMatchesActiveGet200ResponseInner(val *ApiMatchesActiveGet200ResponseInner) *NullableApiMatchesActiveGet200ResponseInner {
	return &NullableApiMatchesActiveGet200ResponseInner{value: val, isSet: true}
}

func (v NullableApiMatchesActiveGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMatchesActiveGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


