/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 0.5.0-rev.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative{}

// ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative struct for ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative
type ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative struct {
	// Which player deploys first in DeploymentPhase.
	DeployFirst string `json:"deployFirst"`
	// Which player attacks first in AttackPhase.
	AttackFirst string `json:"attackFirst"`
}

type _ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative

// NewApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative instantiates a new ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative(deployFirst string, attackFirst string) *ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative {
	this := ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative{}
	this.DeployFirst = deployFirst
	this.AttackFirst = attackFirst
	return &this
}

// NewApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiativeWithDefaults instantiates a new ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiativeWithDefaults() *ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative {
	this := ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative{}
	var deployFirst string = "P2"
	this.DeployFirst = deployFirst
	var attackFirst string = "P1"
	this.AttackFirst = attackFirst
	return &this
}

// GetDeployFirst returns the DeployFirst field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) GetDeployFirst() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeployFirst
}

// GetDeployFirstOk returns a tuple with the DeployFirst field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) GetDeployFirstOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeployFirst, true
}

// SetDeployFirst sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) SetDeployFirst(v string) {
	o.DeployFirst = v
}

// GetAttackFirst returns the AttackFirst field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) GetAttackFirst() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttackFirst
}

// GetAttackFirstOk returns a tuple with the AttackFirst field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) GetAttackFirstOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttackFirst, true
}

// SetAttackFirst sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) SetAttackFirst(v string) {
	o.AttackFirst = v
}

func (o ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deployFirst"] = o.DeployFirst
	toSerialize["attackFirst"] = o.AttackFirst
	return toSerialize, nil
}

func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deployFirst",
		"attackFirst",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative := _ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative)

	if err != nil {
		return err
	}

	*o = ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative(varApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative)

	return err
}

type NullableApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative struct {
	value *ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative
	isSet bool
}

func (v NullableApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) Get() *ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative {
	return v.value
}

func (v *NullableApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) Set(val *ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative(val *ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) *NullableApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative {
	return &NullableApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative{value: val, isSet: true}
}

func (v NullableApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


