/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 0.5.0-rev.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner{}

// ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner struct for ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner
type ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner struct {
	// Opaque deterministic card ID. Format: [Timestamp]::[MatchID]::[PlayerID]::[TurnNumber]::[DrawIndex]. Generated at draw-time. No card info is encoded into the suffix.
	Id string `json:"id"`
	// Card suit. Determines boundary effects during attack resolution: ♦ Diamond (double defense at Card→Card boundary), ♥ Heart (death shield at Card→Player boundary), ♣ Club (double overflow after first destruction), ♠ Spade (double LP damage at Card→Player boundary). See RULES.md §9.
	Suit string `json:"suit"`
	// Card face symbol. One of: A (Ace), 2-9, T (Ten), J (Jack), Q (Queen), K (King). Maps to value via RANK_VALUES lookup.
	Face string `json:"face" validate:"regexp=^[A2-9TJQK]$"`
	// Numeric combat value. A=1, 2-9=face value, T=10, J/Q/K=11. Used as base damage in attack resolution.
	Value int32 `json:"value"`
	// Card type classification. Governs destruction eligibility under Classic Aces (§10) and Classic Face Cards (§11) rules. Aces are only destroyed by other aces at rank 0. Face cards follow a hierarchy: J→J, Q→J/Q, K→J/Q/K.
	Type string `json:"type"`
}

type _ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner

// NewApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner instantiates a new ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner(id string, suit string, face string, value int32, type_ string) *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner {
	this := ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner{}
	this.Id = id
	this.Suit = suit
	this.Face = face
	this.Value = value
	this.Type = type_
	return &this
}

// NewApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInnerWithDefaults instantiates a new ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInnerWithDefaults() *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner {
	this := ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner{}
	return &this
}

// GetId returns the Id field value
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) SetId(v string) {
	o.Id = v
}

// GetSuit returns the Suit field value
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) GetSuit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Suit
}

// GetSuitOk returns a tuple with the Suit field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) GetSuitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Suit, true
}

// SetSuit sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) SetSuit(v string) {
	o.Suit = v
}

// GetFace returns the Face field value
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) GetFace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Face
}

// GetFaceOk returns a tuple with the Face field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) GetFaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Face, true
}

// SetFace sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) SetFace(v string) {
	o.Face = v
}

// GetValue returns the Value field value
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) GetValue() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) GetValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) SetValue(v int32) {
	o.Value = v
}

// GetType returns the Type field value
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) SetType(v string) {
	o.Type = v
}

func (o ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["suit"] = o.Suit
	toSerialize["face"] = o.Face
	toSerialize["value"] = o.Value
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"suit",
		"face",
		"value",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner := _ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner)

	if err != nil {
		return err
	}

	*o = ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner(varApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner)

	return err
}

type NullableApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner struct {
	value *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner
	isSet bool
}

func (v NullableApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) Get() *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner {
	return v.value
}

func (v *NullableApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) Set(val *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner(val *ApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) *NullableApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner {
	return &NullableApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner{value: val, isSet: true}
}

func (v NullableApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMatchesIdActionPost200ResponsePreStatePlayersInnerHandInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


