/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction - Authoritative action payload for Phalanx: Duel.
type ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction struct {
	ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf *ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf
	ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1 *ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1
	ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2 *ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2
	ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3 *ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3
	ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4 *ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4
	ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5 *ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5
}

// ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOfAsApiMatchesIdReplayGet200ResponseTransactionLogInnerAction is a convenience function that returns ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf wrapped in ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction
func ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOfAsApiMatchesIdReplayGet200ResponseTransactionLogInnerAction(v *ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf) ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction {
	return ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction{
		ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf: v,
	}
}

// ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1AsApiMatchesIdReplayGet200ResponseTransactionLogInnerAction is a convenience function that returns ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1 wrapped in ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction
func ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1AsApiMatchesIdReplayGet200ResponseTransactionLogInnerAction(v *ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1) ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction {
	return ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction{
		ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1: v,
	}
}

// ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2AsApiMatchesIdReplayGet200ResponseTransactionLogInnerAction is a convenience function that returns ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2 wrapped in ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction
func ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2AsApiMatchesIdReplayGet200ResponseTransactionLogInnerAction(v *ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2) ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction {
	return ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction{
		ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2: v,
	}
}

// ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3AsApiMatchesIdReplayGet200ResponseTransactionLogInnerAction is a convenience function that returns ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3 wrapped in ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction
func ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3AsApiMatchesIdReplayGet200ResponseTransactionLogInnerAction(v *ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3) ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction {
	return ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction{
		ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3: v,
	}
}

// ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4AsApiMatchesIdReplayGet200ResponseTransactionLogInnerAction is a convenience function that returns ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4 wrapped in ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction
func ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4AsApiMatchesIdReplayGet200ResponseTransactionLogInnerAction(v *ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4) ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction {
	return ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction{
		ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4: v,
	}
}

// ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5AsApiMatchesIdReplayGet200ResponseTransactionLogInnerAction is a convenience function that returns ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5 wrapped in ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction
func ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5AsApiMatchesIdReplayGet200ResponseTransactionLogInnerAction(v *ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5) ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction {
	return ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction{
		ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf
	err = newStrictDecoder(data).Decode(&dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf)
	if err == nil {
		jsonApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf, _ := json.Marshal(dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf)
		if string(jsonApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf) == "{}" { // empty struct
			dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf = nil
		} else {
			if err = validator.Validate(dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf); err != nil {
				dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf = nil
	}

	// try to unmarshal data into ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1
	err = newStrictDecoder(data).Decode(&dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1)
	if err == nil {
		jsonApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1, _ := json.Marshal(dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1)
		if string(jsonApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1) == "{}" { // empty struct
			dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1 = nil
		} else {
			if err = validator.Validate(dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1); err != nil {
				dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1 = nil
	}

	// try to unmarshal data into ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2
	err = newStrictDecoder(data).Decode(&dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2)
	if err == nil {
		jsonApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2, _ := json.Marshal(dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2)
		if string(jsonApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2) == "{}" { // empty struct
			dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2 = nil
		} else {
			if err = validator.Validate(dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2); err != nil {
				dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2 = nil
	}

	// try to unmarshal data into ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3
	err = newStrictDecoder(data).Decode(&dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3)
	if err == nil {
		jsonApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3, _ := json.Marshal(dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3)
		if string(jsonApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3) == "{}" { // empty struct
			dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3 = nil
		} else {
			if err = validator.Validate(dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3); err != nil {
				dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3 = nil
	}

	// try to unmarshal data into ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4
	err = newStrictDecoder(data).Decode(&dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4)
	if err == nil {
		jsonApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4, _ := json.Marshal(dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4)
		if string(jsonApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4) == "{}" { // empty struct
			dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4 = nil
		} else {
			if err = validator.Validate(dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4); err != nil {
				dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4 = nil
	}

	// try to unmarshal data into ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5
	err = newStrictDecoder(data).Decode(&dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5)
	if err == nil {
		jsonApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5, _ := json.Marshal(dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5)
		if string(jsonApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5) == "{}" { // empty struct
			dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5 = nil
		} else {
			if err = validator.Validate(dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5); err != nil {
				dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf = nil
		dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1 = nil
		dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2 = nil
		dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3 = nil
		dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4 = nil
		dst.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) MarshalJSON() ([]byte, error) {
	if src.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf != nil {
		return json.Marshal(&src.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf)
	}

	if src.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1 != nil {
		return json.Marshal(&src.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1)
	}

	if src.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2 != nil {
		return json.Marshal(&src.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2)
	}

	if src.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3 != nil {
		return json.Marshal(&src.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3)
	}

	if src.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4 != nil {
		return json.Marshal(&src.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4)
	}

	if src.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5 != nil {
		return json.Marshal(&src.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf != nil {
		return obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf
	}

	if obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1 != nil {
		return obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1
	}

	if obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2 != nil {
		return obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2
	}

	if obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3 != nil {
		return obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3
	}

	if obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4 != nil {
		return obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4
	}

	if obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5 != nil {
		return obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) GetActualInstanceValue() (interface{}) {
	if obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf != nil {
		return *obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf
	}

	if obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1 != nil {
		return *obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf1
	}

	if obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2 != nil {
		return *obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf2
	}

	if obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3 != nil {
		return *obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf3
	}

	if obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4 != nil {
		return *obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf4
	}

	if obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5 != nil {
		return *obj.ApiMatchesIdReplayGet200ResponseTransactionLogInnerActionOneOf5
	}

	// all schemas are nil
	return nil
}

type NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerAction struct {
	value *ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction
	isSet bool
}

func (v NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) Get() *ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction {
	return v.value
}

func (v *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) Set(val *ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMatchesIdReplayGet200ResponseTransactionLogInnerAction(val *ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerAction {
	return &NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerAction{value: val, isSet: true}
}

func (v NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


