/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiMatchesIdReplayGet200ResponseParamsClassicHand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMatchesIdReplayGet200ResponseParamsClassicHand{}

// ApiMatchesIdReplayGet200ResponseParamsClassicHand struct for ApiMatchesIdReplayGet200ResponseParamsClassicHand
type ApiMatchesIdReplayGet200ResponseParamsClassicHand struct {
	// Maximum hand size. Must be ≤ columns (§3.3). Default: 4.
	MaxHandSize int32 `json:"maxHandSize"`
}

type _ApiMatchesIdReplayGet200ResponseParamsClassicHand ApiMatchesIdReplayGet200ResponseParamsClassicHand

// NewApiMatchesIdReplayGet200ResponseParamsClassicHand instantiates a new ApiMatchesIdReplayGet200ResponseParamsClassicHand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMatchesIdReplayGet200ResponseParamsClassicHand(maxHandSize int32) *ApiMatchesIdReplayGet200ResponseParamsClassicHand {
	this := ApiMatchesIdReplayGet200ResponseParamsClassicHand{}
	this.MaxHandSize = maxHandSize
	return &this
}

// NewApiMatchesIdReplayGet200ResponseParamsClassicHandWithDefaults instantiates a new ApiMatchesIdReplayGet200ResponseParamsClassicHand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMatchesIdReplayGet200ResponseParamsClassicHandWithDefaults() *ApiMatchesIdReplayGet200ResponseParamsClassicHand {
	this := ApiMatchesIdReplayGet200ResponseParamsClassicHand{}
	var maxHandSize int32 = 4
	this.MaxHandSize = maxHandSize
	return &this
}

// GetMaxHandSize returns the MaxHandSize field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicHand) GetMaxHandSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxHandSize
}

// GetMaxHandSizeOk returns a tuple with the MaxHandSize field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicHand) GetMaxHandSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxHandSize, true
}

// SetMaxHandSize sets field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicHand) SetMaxHandSize(v int32) {
	o.MaxHandSize = v
}

func (o ApiMatchesIdReplayGet200ResponseParamsClassicHand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMatchesIdReplayGet200ResponseParamsClassicHand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["maxHandSize"] = o.MaxHandSize
	return toSerialize, nil
}

func (o *ApiMatchesIdReplayGet200ResponseParamsClassicHand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"maxHandSize",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiMatchesIdReplayGet200ResponseParamsClassicHand := _ApiMatchesIdReplayGet200ResponseParamsClassicHand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiMatchesIdReplayGet200ResponseParamsClassicHand)

	if err != nil {
		return err
	}

	*o = ApiMatchesIdReplayGet200ResponseParamsClassicHand(varApiMatchesIdReplayGet200ResponseParamsClassicHand)

	return err
}

type NullableApiMatchesIdReplayGet200ResponseParamsClassicHand struct {
	value *ApiMatchesIdReplayGet200ResponseParamsClassicHand
	isSet bool
}

func (v NullableApiMatchesIdReplayGet200ResponseParamsClassicHand) Get() *ApiMatchesIdReplayGet200ResponseParamsClassicHand {
	return v.value
}

func (v *NullableApiMatchesIdReplayGet200ResponseParamsClassicHand) Set(val *ApiMatchesIdReplayGet200ResponseParamsClassicHand) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMatchesIdReplayGet200ResponseParamsClassicHand) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMatchesIdReplayGet200ResponseParamsClassicHand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMatchesIdReplayGet200ResponseParamsClassicHand(val *ApiMatchesIdReplayGet200ResponseParamsClassicHand) *NullableApiMatchesIdReplayGet200ResponseParamsClassicHand {
	return &NullableApiMatchesIdReplayGet200ResponseParamsClassicHand{value: val, isSet: true}
}

func (v NullableApiMatchesIdReplayGet200ResponseParamsClassicHand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMatchesIdReplayGet200ResponseParamsClassicHand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


