/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/RULES.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/EVENT_SCHEMAS.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 0.5.0-rev.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails - struct for MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails
type MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails struct {
	MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf
	MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1 *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1
	MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2 *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2
	MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3 *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3
	MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4 *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4
}

// MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOfAsMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails is a convenience function that returns MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf wrapped in MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails
func MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOfAsMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails(v *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf) MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails {
	return MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails{
		MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf: v,
	}
}

// MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1AsMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails is a convenience function that returns MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1 wrapped in MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails
func MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1AsMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails(v *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1) MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails {
	return MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails{
		MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1: v,
	}
}

// MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2AsMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails is a convenience function that returns MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2 wrapped in MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails
func MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2AsMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails(v *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2) MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails {
	return MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails{
		MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2: v,
	}
}

// MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3AsMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails is a convenience function that returns MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3 wrapped in MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails
func MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3AsMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails(v *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3) MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails {
	return MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails{
		MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3: v,
	}
}

// MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4AsMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails is a convenience function that returns MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4 wrapped in MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails
func MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4AsMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails(v *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4) MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails {
	return MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails{
		MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf
	err = newStrictDecoder(data).Decode(&dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf)
	if err == nil {
		jsonMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf, _ := json.Marshal(dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf)
		if string(jsonMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf) == "{}" { // empty struct
			dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf = nil
		} else {
			if err = validator.Validate(dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf); err != nil {
				dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf = nil
	}

	// try to unmarshal data into MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1
	err = newStrictDecoder(data).Decode(&dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1)
	if err == nil {
		jsonMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1, _ := json.Marshal(dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1)
		if string(jsonMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1) == "{}" { // empty struct
			dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1 = nil
		} else {
			if err = validator.Validate(dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1); err != nil {
				dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1 = nil
	}

	// try to unmarshal data into MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2
	err = newStrictDecoder(data).Decode(&dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2)
	if err == nil {
		jsonMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2, _ := json.Marshal(dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2)
		if string(jsonMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2) == "{}" { // empty struct
			dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2 = nil
		} else {
			if err = validator.Validate(dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2); err != nil {
				dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2 = nil
	}

	// try to unmarshal data into MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3
	err = newStrictDecoder(data).Decode(&dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3)
	if err == nil {
		jsonMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3, _ := json.Marshal(dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3)
		if string(jsonMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3) == "{}" { // empty struct
			dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3 = nil
		} else {
			if err = validator.Validate(dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3); err != nil {
				dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3 = nil
	}

	// try to unmarshal data into MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4
	err = newStrictDecoder(data).Decode(&dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4)
	if err == nil {
		jsonMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4, _ := json.Marshal(dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4)
		if string(jsonMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4) == "{}" { // empty struct
			dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4 = nil
		} else {
			if err = validator.Validate(dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4); err != nil {
				dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4 = nil
			} else {
				match++
			}
		}
	} else {
		dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf = nil
		dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1 = nil
		dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2 = nil
		dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3 = nil
		dst.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails) MarshalJSON() ([]byte, error) {
	if src.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf != nil {
		return json.Marshal(&src.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf)
	}

	if src.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1 != nil {
		return json.Marshal(&src.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1)
	}

	if src.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2 != nil {
		return json.Marshal(&src.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2)
	}

	if src.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3 != nil {
		return json.Marshal(&src.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3)
	}

	if src.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4 != nil {
		return json.Marshal(&src.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf != nil {
		return obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf
	}

	if obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1 != nil {
		return obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1
	}

	if obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2 != nil {
		return obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2
	}

	if obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3 != nil {
		return obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3
	}

	if obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4 != nil {
		return obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails) GetActualInstanceValue() (interface{}) {
	if obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf != nil {
		return *obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf
	}

	if obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1 != nil {
		return *obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf1
	}

	if obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2 != nil {
		return *obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf2
	}

	if obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3 != nil {
		return *obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf3
	}

	if obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4 != nil {
		return *obj.MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetailsOneOf4
	}

	// all schemas are nil
	return nil
}

type NullableMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails struct {
	value *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails
	isSet bool
}

func (v NullableMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails) Get() *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails {
	return v.value
}

func (v *NullableMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails) Set(val *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails(val *MatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails) *NullableMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails {
	return &NullableMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails{value: val, isSet: true}
}

func (v NullableMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatchesIdSimulatePost200ResponsePreStateTransactionLogInnerDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


