/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ApiUsersUserIdAchievementsGet200ResponseAchievementsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiUsersUserIdAchievementsGet200ResponseAchievementsInner{}

// ApiUsersUserIdAchievementsGet200ResponseAchievementsInner A single achievement earned by a player.
type ApiUsersUserIdAchievementsGet200ResponseAchievementsInner struct {
	// Unique achievement record ID.
	Id string `json:"id" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	// Player who earned this achievement.
	UserId string `json:"userId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	// Achievement type identifier. Each type is awarded at most once per player.
	Type string `json:"type"`
	// When the achievement was awarded.
	AwardedAt time.Time `json:"awardedAt" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	MatchId NullableString `json:"matchId"`
	// Achievement-specific context data (e.g., winning LP, turn count).
	Metadata map[string]interface{} `json:"metadata"`
}

type _ApiUsersUserIdAchievementsGet200ResponseAchievementsInner ApiUsersUserIdAchievementsGet200ResponseAchievementsInner

// NewApiUsersUserIdAchievementsGet200ResponseAchievementsInner instantiates a new ApiUsersUserIdAchievementsGet200ResponseAchievementsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiUsersUserIdAchievementsGet200ResponseAchievementsInner(id string, userId string, type_ string, awardedAt time.Time, matchId NullableString, metadata map[string]interface{}) *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner {
	this := ApiUsersUserIdAchievementsGet200ResponseAchievementsInner{}
	this.Id = id
	this.UserId = userId
	this.Type = type_
	this.AwardedAt = awardedAt
	this.MatchId = matchId
	this.Metadata = metadata
	return &this
}

// NewApiUsersUserIdAchievementsGet200ResponseAchievementsInnerWithDefaults instantiates a new ApiUsersUserIdAchievementsGet200ResponseAchievementsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiUsersUserIdAchievementsGet200ResponseAchievementsInnerWithDefaults() *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner {
	this := ApiUsersUserIdAchievementsGet200ResponseAchievementsInner{}
	return &this
}

// GetId returns the Id field value
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) SetId(v string) {
	o.Id = v
}

// GetUserId returns the UserId field value
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) SetUserId(v string) {
	o.UserId = v
}

// GetType returns the Type field value
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) SetType(v string) {
	o.Type = v
}

// GetAwardedAt returns the AwardedAt field value
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) GetAwardedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.AwardedAt
}

// GetAwardedAtOk returns a tuple with the AwardedAt field value
// and a boolean to check if the value has been set.
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) GetAwardedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AwardedAt, true
}

// SetAwardedAt sets field value
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) SetAwardedAt(v time.Time) {
	o.AwardedAt = v
}

// GetMatchId returns the MatchId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) GetMatchId() string {
	if o == nil || o.MatchId.Get() == nil {
		var ret string
		return ret
	}

	return *o.MatchId.Get()
}

// GetMatchIdOk returns a tuple with the MatchId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) GetMatchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MatchId.Get(), o.MatchId.IsSet()
}

// SetMatchId sets field value
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) SetMatchId(v string) {
	o.MatchId.Set(&v)
}

// GetMetadata returns the Metadata field value
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["userId"] = o.UserId
	toSerialize["type"] = o.Type
	toSerialize["awardedAt"] = o.AwardedAt
	toSerialize["matchId"] = o.MatchId.Get()
	toSerialize["metadata"] = o.Metadata
	return toSerialize, nil
}

func (o *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"userId",
		"type",
		"awardedAt",
		"matchId",
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiUsersUserIdAchievementsGet200ResponseAchievementsInner := _ApiUsersUserIdAchievementsGet200ResponseAchievementsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiUsersUserIdAchievementsGet200ResponseAchievementsInner)

	if err != nil {
		return err
	}

	*o = ApiUsersUserIdAchievementsGet200ResponseAchievementsInner(varApiUsersUserIdAchievementsGet200ResponseAchievementsInner)

	return err
}

type NullableApiUsersUserIdAchievementsGet200ResponseAchievementsInner struct {
	value *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner
	isSet bool
}

func (v NullableApiUsersUserIdAchievementsGet200ResponseAchievementsInner) Get() *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner {
	return v.value
}

func (v *NullableApiUsersUserIdAchievementsGet200ResponseAchievementsInner) Set(val *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiUsersUserIdAchievementsGet200ResponseAchievementsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiUsersUserIdAchievementsGet200ResponseAchievementsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiUsersUserIdAchievementsGet200ResponseAchievementsInner(val *ApiUsersUserIdAchievementsGet200ResponseAchievementsInner) *NullableApiUsersUserIdAchievementsGet200ResponseAchievementsInner {
	return &NullableApiUsersUserIdAchievementsGet200ResponseAchievementsInner{value: val, isSet: true}
}

func (v NullableApiUsersUserIdAchievementsGet200ResponseAchievementsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiUsersUserIdAchievementsGet200ResponseAchievementsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


