/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ApiMatchesMatchIdCommentsGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMatchesMatchIdCommentsGet200ResponseInner{}

// ApiMatchesMatchIdCommentsGet200ResponseInner struct for ApiMatchesMatchIdCommentsGet200ResponseInner
type ApiMatchesMatchIdCommentsGet200ResponseInner struct {
	Id string `json:"id" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	UserId string `json:"userId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	Gamertag string `json:"gamertag"`
	AvatarIcon NullableString `json:"avatarIcon"`
	Content string `json:"content"`
	Step NullableInt32 `json:"step"`
	CreatedAt time.Time `json:"createdAt" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
}

type _ApiMatchesMatchIdCommentsGet200ResponseInner ApiMatchesMatchIdCommentsGet200ResponseInner

// NewApiMatchesMatchIdCommentsGet200ResponseInner instantiates a new ApiMatchesMatchIdCommentsGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMatchesMatchIdCommentsGet200ResponseInner(id string, userId string, gamertag string, avatarIcon NullableString, content string, step NullableInt32, createdAt time.Time) *ApiMatchesMatchIdCommentsGet200ResponseInner {
	this := ApiMatchesMatchIdCommentsGet200ResponseInner{}
	this.Id = id
	this.UserId = userId
	this.Gamertag = gamertag
	this.AvatarIcon = avatarIcon
	this.Content = content
	this.Step = step
	this.CreatedAt = createdAt
	return &this
}

// NewApiMatchesMatchIdCommentsGet200ResponseInnerWithDefaults instantiates a new ApiMatchesMatchIdCommentsGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMatchesMatchIdCommentsGet200ResponseInnerWithDefaults() *ApiMatchesMatchIdCommentsGet200ResponseInner {
	this := ApiMatchesMatchIdCommentsGet200ResponseInner{}
	return &this
}

// GetId returns the Id field value
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) SetId(v string) {
	o.Id = v
}

// GetUserId returns the UserId field value
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) SetUserId(v string) {
	o.UserId = v
}

// GetGamertag returns the Gamertag field value
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetGamertag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Gamertag
}

// GetGamertagOk returns a tuple with the Gamertag field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetGamertagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gamertag, true
}

// SetGamertag sets field value
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) SetGamertag(v string) {
	o.Gamertag = v
}

// GetAvatarIcon returns the AvatarIcon field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetAvatarIcon() string {
	if o == nil || o.AvatarIcon.Get() == nil {
		var ret string
		return ret
	}

	return *o.AvatarIcon.Get()
}

// GetAvatarIconOk returns a tuple with the AvatarIcon field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetAvatarIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvatarIcon.Get(), o.AvatarIcon.IsSet()
}

// SetAvatarIcon sets field value
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) SetAvatarIcon(v string) {
	o.AvatarIcon.Set(&v)
}

// GetContent returns the Content field value
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) SetContent(v string) {
	o.Content = v
}

// GetStep returns the Step field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetStep() int32 {
	if o == nil || o.Step.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Step.Get()
}

// GetStepOk returns a tuple with the Step field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetStepOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Step.Get(), o.Step.IsSet()
}

// SetStep sets field value
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) SetStep(v int32) {
	o.Step.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o ApiMatchesMatchIdCommentsGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMatchesMatchIdCommentsGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["userId"] = o.UserId
	toSerialize["gamertag"] = o.Gamertag
	toSerialize["avatarIcon"] = o.AvatarIcon.Get()
	toSerialize["content"] = o.Content
	toSerialize["step"] = o.Step.Get()
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

func (o *ApiMatchesMatchIdCommentsGet200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"userId",
		"gamertag",
		"avatarIcon",
		"content",
		"step",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiMatchesMatchIdCommentsGet200ResponseInner := _ApiMatchesMatchIdCommentsGet200ResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiMatchesMatchIdCommentsGet200ResponseInner)

	if err != nil {
		return err
	}

	*o = ApiMatchesMatchIdCommentsGet200ResponseInner(varApiMatchesMatchIdCommentsGet200ResponseInner)

	return err
}

type NullableApiMatchesMatchIdCommentsGet200ResponseInner struct {
	value *ApiMatchesMatchIdCommentsGet200ResponseInner
	isSet bool
}

func (v NullableApiMatchesMatchIdCommentsGet200ResponseInner) Get() *ApiMatchesMatchIdCommentsGet200ResponseInner {
	return v.value
}

func (v *NullableApiMatchesMatchIdCommentsGet200ResponseInner) Set(val *ApiMatchesMatchIdCommentsGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMatchesMatchIdCommentsGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMatchesMatchIdCommentsGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMatchesMatchIdCommentsGet200ResponseInner(val *ApiMatchesMatchIdCommentsGet200ResponseInner) *NullableApiMatchesMatchIdCommentsGet200ResponseInner {
	return &NullableApiMatchesMatchIdCommentsGet200ResponseInner{value: val, isSet: true}
}

func (v NullableApiMatchesMatchIdCommentsGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMatchesMatchIdCommentsGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


