/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield{}

// ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield struct for ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield
type ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield struct {
	// Number of ranks (rows) per column. Default: 2. Max: 12 (§3.3).
	Rows int32 `json:"rows"`
	// Number of columns per player board. Default: 4. Max: 12 (§3.3).
	Columns int32 `json:"columns"`
}

type _ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield

// NewApiMatchesIdReplayGet200ResponseParamsClassicBattlefield instantiates a new ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMatchesIdReplayGet200ResponseParamsClassicBattlefield(rows int32, columns int32) *ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield {
	this := ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield{}
	this.Rows = rows
	this.Columns = columns
	return &this
}

// NewApiMatchesIdReplayGet200ResponseParamsClassicBattlefieldWithDefaults instantiates a new ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMatchesIdReplayGet200ResponseParamsClassicBattlefieldWithDefaults() *ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield {
	this := ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield{}
	var rows int32 = 2
	this.Rows = rows
	var columns int32 = 4
	this.Columns = columns
	return &this
}

// GetRows returns the Rows field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) GetRows() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) GetRowsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rows, true
}

// SetRows sets field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) SetRows(v int32) {
	o.Rows = v
}

// GetColumns returns the Columns field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) GetColumns() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) GetColumnsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Columns, true
}

// SetColumns sets field value
func (o *ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) SetColumns(v int32) {
	o.Columns = v
}

func (o ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rows"] = o.Rows
	toSerialize["columns"] = o.Columns
	return toSerialize, nil
}

func (o *ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rows",
		"columns",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiMatchesIdReplayGet200ResponseParamsClassicBattlefield := _ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiMatchesIdReplayGet200ResponseParamsClassicBattlefield)

	if err != nil {
		return err
	}

	*o = ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield(varApiMatchesIdReplayGet200ResponseParamsClassicBattlefield)

	return err
}

type NullableApiMatchesIdReplayGet200ResponseParamsClassicBattlefield struct {
	value *ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield
	isSet bool
}

func (v NullableApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) Get() *ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield {
	return v.value
}

func (v *NullableApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) Set(val *ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMatchesIdReplayGet200ResponseParamsClassicBattlefield(val *ApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) *NullableApiMatchesIdReplayGet200ResponseParamsClassicBattlefield {
	return &NullableApiMatchesIdReplayGet200ResponseParamsClassicBattlefield{value: val, isSet: true}
}

func (v NullableApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMatchesIdReplayGet200ResponseParamsClassicBattlefield) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


