/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ApiProfilesUserIdGet200ResponseRecentMatchesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiProfilesUserIdGet200ResponseRecentMatchesInner{}

// ApiProfilesUserIdGet200ResponseRecentMatchesInner struct for ApiProfilesUserIdGet200ResponseRecentMatchesInner
type ApiProfilesUserIdGet200ResponseRecentMatchesInner struct {
	MatchId string `json:"matchId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	Result string `json:"result"`
	Mode string `json:"mode"`
	OpponentName NullableString `json:"opponentName"`
	CompletedAt time.Time `json:"completedAt" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	TurnNumber NullableInt32 `json:"turnNumber"`
}

type _ApiProfilesUserIdGet200ResponseRecentMatchesInner ApiProfilesUserIdGet200ResponseRecentMatchesInner

// NewApiProfilesUserIdGet200ResponseRecentMatchesInner instantiates a new ApiProfilesUserIdGet200ResponseRecentMatchesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiProfilesUserIdGet200ResponseRecentMatchesInner(matchId string, result string, mode string, opponentName NullableString, completedAt time.Time, turnNumber NullableInt32) *ApiProfilesUserIdGet200ResponseRecentMatchesInner {
	this := ApiProfilesUserIdGet200ResponseRecentMatchesInner{}
	this.MatchId = matchId
	this.Result = result
	this.Mode = mode
	this.OpponentName = opponentName
	this.CompletedAt = completedAt
	this.TurnNumber = turnNumber
	return &this
}

// NewApiProfilesUserIdGet200ResponseRecentMatchesInnerWithDefaults instantiates a new ApiProfilesUserIdGet200ResponseRecentMatchesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiProfilesUserIdGet200ResponseRecentMatchesInnerWithDefaults() *ApiProfilesUserIdGet200ResponseRecentMatchesInner {
	this := ApiProfilesUserIdGet200ResponseRecentMatchesInner{}
	return &this
}

// GetMatchId returns the MatchId field value
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) GetMatchId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MatchId
}

// GetMatchIdOk returns a tuple with the MatchId field value
// and a boolean to check if the value has been set.
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) GetMatchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MatchId, true
}

// SetMatchId sets field value
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) SetMatchId(v string) {
	o.MatchId = v
}

// GetResult returns the Result field value
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) GetResult() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) GetResultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) SetResult(v string) {
	o.Result = v
}

// GetMode returns the Mode field value
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) SetMode(v string) {
	o.Mode = v
}

// GetOpponentName returns the OpponentName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) GetOpponentName() string {
	if o == nil || o.OpponentName.Get() == nil {
		var ret string
		return ret
	}

	return *o.OpponentName.Get()
}

// GetOpponentNameOk returns a tuple with the OpponentName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) GetOpponentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OpponentName.Get(), o.OpponentName.IsSet()
}

// SetOpponentName sets field value
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) SetOpponentName(v string) {
	o.OpponentName.Set(&v)
}

// GetCompletedAt returns the CompletedAt field value
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) GetCompletedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CompletedAt
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value
// and a boolean to check if the value has been set.
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompletedAt, true
}

// SetCompletedAt sets field value
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) SetCompletedAt(v time.Time) {
	o.CompletedAt = v
}

// GetTurnNumber returns the TurnNumber field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) GetTurnNumber() int32 {
	if o == nil || o.TurnNumber.Get() == nil {
		var ret int32
		return ret
	}

	return *o.TurnNumber.Get()
}

// GetTurnNumberOk returns a tuple with the TurnNumber field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) GetTurnNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TurnNumber.Get(), o.TurnNumber.IsSet()
}

// SetTurnNumber sets field value
func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) SetTurnNumber(v int32) {
	o.TurnNumber.Set(&v)
}

func (o ApiProfilesUserIdGet200ResponseRecentMatchesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiProfilesUserIdGet200ResponseRecentMatchesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["matchId"] = o.MatchId
	toSerialize["result"] = o.Result
	toSerialize["mode"] = o.Mode
	toSerialize["opponentName"] = o.OpponentName.Get()
	toSerialize["completedAt"] = o.CompletedAt
	toSerialize["turnNumber"] = o.TurnNumber.Get()
	return toSerialize, nil
}

func (o *ApiProfilesUserIdGet200ResponseRecentMatchesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"matchId",
		"result",
		"mode",
		"opponentName",
		"completedAt",
		"turnNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiProfilesUserIdGet200ResponseRecentMatchesInner := _ApiProfilesUserIdGet200ResponseRecentMatchesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiProfilesUserIdGet200ResponseRecentMatchesInner)

	if err != nil {
		return err
	}

	*o = ApiProfilesUserIdGet200ResponseRecentMatchesInner(varApiProfilesUserIdGet200ResponseRecentMatchesInner)

	return err
}

type NullableApiProfilesUserIdGet200ResponseRecentMatchesInner struct {
	value *ApiProfilesUserIdGet200ResponseRecentMatchesInner
	isSet bool
}

func (v NullableApiProfilesUserIdGet200ResponseRecentMatchesInner) Get() *ApiProfilesUserIdGet200ResponseRecentMatchesInner {
	return v.value
}

func (v *NullableApiProfilesUserIdGet200ResponseRecentMatchesInner) Set(val *ApiProfilesUserIdGet200ResponseRecentMatchesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiProfilesUserIdGet200ResponseRecentMatchesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiProfilesUserIdGet200ResponseRecentMatchesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiProfilesUserIdGet200ResponseRecentMatchesInner(val *ApiProfilesUserIdGet200ResponseRecentMatchesInner) *NullableApiProfilesUserIdGet200ResponseRecentMatchesInner {
	return &NullableApiProfilesUserIdGet200ResponseRecentMatchesInner{value: val, isSet: true}
}

func (v NullableApiProfilesUserIdGet200ResponseRecentMatchesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiProfilesUserIdGet200ResponseRecentMatchesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


