/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner{}

// ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner struct for ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner
type ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner struct {
	Target string `json:"target"`
	Card *ApiMatchesIdReplayGet200ResponsePlayersInnerHandInner `json:"card,omitempty"`
	IncomingDamage *int32 `json:"incomingDamage,omitempty"`
	Damage int32 `json:"damage"`
	EffectiveHp *int32 `json:"effectiveHp,omitempty"`
	HpBefore *int32 `json:"hpBefore,omitempty"`
	HpAfter *int32 `json:"hpAfter,omitempty"`
	LpBefore *int32 `json:"lpBefore,omitempty"`
	LpAfter *int32 `json:"lpAfter,omitempty"`
	Absorbed *int32 `json:"absorbed,omitempty"`
	Overflow *int32 `json:"overflow,omitempty"`
	Remaining *int32 `json:"remaining,omitempty"`
	Destroyed *bool `json:"destroyed,omitempty"`
	Bonuses []string `json:"bonuses,omitempty"`
}

type _ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner

// NewApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner instantiates a new ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner(target string, damage int32) *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner {
	this := ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner{}
	this.Target = target
	this.Damage = damage
	return &this
}

// NewApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInnerWithDefaults instantiates a new ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInnerWithDefaults() *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner {
	this := ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner{}
	return &this
}

// GetTarget returns the Target field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetTarget(v string) {
	o.Target = v
}

// GetCard returns the Card field value if set, zero value otherwise.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetCard() ApiMatchesIdReplayGet200ResponsePlayersInnerHandInner {
	if o == nil || IsNil(o.Card) {
		var ret ApiMatchesIdReplayGet200ResponsePlayersInnerHandInner
		return ret
	}
	return *o.Card
}

// GetCardOk returns a tuple with the Card field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetCardOk() (*ApiMatchesIdReplayGet200ResponsePlayersInnerHandInner, bool) {
	if o == nil || IsNil(o.Card) {
		return nil, false
	}
	return o.Card, true
}

// HasCard returns a boolean if a field has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) HasCard() bool {
	if o != nil && !IsNil(o.Card) {
		return true
	}

	return false
}

// SetCard gets a reference to the given ApiMatchesIdReplayGet200ResponsePlayersInnerHandInner and assigns it to the Card field.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetCard(v ApiMatchesIdReplayGet200ResponsePlayersInnerHandInner) {
	o.Card = &v
}

// GetIncomingDamage returns the IncomingDamage field value if set, zero value otherwise.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetIncomingDamage() int32 {
	if o == nil || IsNil(o.IncomingDamage) {
		var ret int32
		return ret
	}
	return *o.IncomingDamage
}

// GetIncomingDamageOk returns a tuple with the IncomingDamage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetIncomingDamageOk() (*int32, bool) {
	if o == nil || IsNil(o.IncomingDamage) {
		return nil, false
	}
	return o.IncomingDamage, true
}

// HasIncomingDamage returns a boolean if a field has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) HasIncomingDamage() bool {
	if o != nil && !IsNil(o.IncomingDamage) {
		return true
	}

	return false
}

// SetIncomingDamage gets a reference to the given int32 and assigns it to the IncomingDamage field.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetIncomingDamage(v int32) {
	o.IncomingDamage = &v
}

// GetDamage returns the Damage field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetDamage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Damage
}

// GetDamageOk returns a tuple with the Damage field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetDamageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Damage, true
}

// SetDamage sets field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetDamage(v int32) {
	o.Damage = v
}

// GetEffectiveHp returns the EffectiveHp field value if set, zero value otherwise.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetEffectiveHp() int32 {
	if o == nil || IsNil(o.EffectiveHp) {
		var ret int32
		return ret
	}
	return *o.EffectiveHp
}

// GetEffectiveHpOk returns a tuple with the EffectiveHp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetEffectiveHpOk() (*int32, bool) {
	if o == nil || IsNil(o.EffectiveHp) {
		return nil, false
	}
	return o.EffectiveHp, true
}

// HasEffectiveHp returns a boolean if a field has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) HasEffectiveHp() bool {
	if o != nil && !IsNil(o.EffectiveHp) {
		return true
	}

	return false
}

// SetEffectiveHp gets a reference to the given int32 and assigns it to the EffectiveHp field.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetEffectiveHp(v int32) {
	o.EffectiveHp = &v
}

// GetHpBefore returns the HpBefore field value if set, zero value otherwise.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetHpBefore() int32 {
	if o == nil || IsNil(o.HpBefore) {
		var ret int32
		return ret
	}
	return *o.HpBefore
}

// GetHpBeforeOk returns a tuple with the HpBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetHpBeforeOk() (*int32, bool) {
	if o == nil || IsNil(o.HpBefore) {
		return nil, false
	}
	return o.HpBefore, true
}

// HasHpBefore returns a boolean if a field has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) HasHpBefore() bool {
	if o != nil && !IsNil(o.HpBefore) {
		return true
	}

	return false
}

// SetHpBefore gets a reference to the given int32 and assigns it to the HpBefore field.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetHpBefore(v int32) {
	o.HpBefore = &v
}

// GetHpAfter returns the HpAfter field value if set, zero value otherwise.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetHpAfter() int32 {
	if o == nil || IsNil(o.HpAfter) {
		var ret int32
		return ret
	}
	return *o.HpAfter
}

// GetHpAfterOk returns a tuple with the HpAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetHpAfterOk() (*int32, bool) {
	if o == nil || IsNil(o.HpAfter) {
		return nil, false
	}
	return o.HpAfter, true
}

// HasHpAfter returns a boolean if a field has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) HasHpAfter() bool {
	if o != nil && !IsNil(o.HpAfter) {
		return true
	}

	return false
}

// SetHpAfter gets a reference to the given int32 and assigns it to the HpAfter field.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetHpAfter(v int32) {
	o.HpAfter = &v
}

// GetLpBefore returns the LpBefore field value if set, zero value otherwise.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetLpBefore() int32 {
	if o == nil || IsNil(o.LpBefore) {
		var ret int32
		return ret
	}
	return *o.LpBefore
}

// GetLpBeforeOk returns a tuple with the LpBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetLpBeforeOk() (*int32, bool) {
	if o == nil || IsNil(o.LpBefore) {
		return nil, false
	}
	return o.LpBefore, true
}

// HasLpBefore returns a boolean if a field has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) HasLpBefore() bool {
	if o != nil && !IsNil(o.LpBefore) {
		return true
	}

	return false
}

// SetLpBefore gets a reference to the given int32 and assigns it to the LpBefore field.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetLpBefore(v int32) {
	o.LpBefore = &v
}

// GetLpAfter returns the LpAfter field value if set, zero value otherwise.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetLpAfter() int32 {
	if o == nil || IsNil(o.LpAfter) {
		var ret int32
		return ret
	}
	return *o.LpAfter
}

// GetLpAfterOk returns a tuple with the LpAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetLpAfterOk() (*int32, bool) {
	if o == nil || IsNil(o.LpAfter) {
		return nil, false
	}
	return o.LpAfter, true
}

// HasLpAfter returns a boolean if a field has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) HasLpAfter() bool {
	if o != nil && !IsNil(o.LpAfter) {
		return true
	}

	return false
}

// SetLpAfter gets a reference to the given int32 and assigns it to the LpAfter field.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetLpAfter(v int32) {
	o.LpAfter = &v
}

// GetAbsorbed returns the Absorbed field value if set, zero value otherwise.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetAbsorbed() int32 {
	if o == nil || IsNil(o.Absorbed) {
		var ret int32
		return ret
	}
	return *o.Absorbed
}

// GetAbsorbedOk returns a tuple with the Absorbed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetAbsorbedOk() (*int32, bool) {
	if o == nil || IsNil(o.Absorbed) {
		return nil, false
	}
	return o.Absorbed, true
}

// HasAbsorbed returns a boolean if a field has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) HasAbsorbed() bool {
	if o != nil && !IsNil(o.Absorbed) {
		return true
	}

	return false
}

// SetAbsorbed gets a reference to the given int32 and assigns it to the Absorbed field.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetAbsorbed(v int32) {
	o.Absorbed = &v
}

// GetOverflow returns the Overflow field value if set, zero value otherwise.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetOverflow() int32 {
	if o == nil || IsNil(o.Overflow) {
		var ret int32
		return ret
	}
	return *o.Overflow
}

// GetOverflowOk returns a tuple with the Overflow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetOverflowOk() (*int32, bool) {
	if o == nil || IsNil(o.Overflow) {
		return nil, false
	}
	return o.Overflow, true
}

// HasOverflow returns a boolean if a field has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) HasOverflow() bool {
	if o != nil && !IsNil(o.Overflow) {
		return true
	}

	return false
}

// SetOverflow gets a reference to the given int32 and assigns it to the Overflow field.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetOverflow(v int32) {
	o.Overflow = &v
}

// GetRemaining returns the Remaining field value if set, zero value otherwise.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetRemaining() int32 {
	if o == nil || IsNil(o.Remaining) {
		var ret int32
		return ret
	}
	return *o.Remaining
}

// GetRemainingOk returns a tuple with the Remaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetRemainingOk() (*int32, bool) {
	if o == nil || IsNil(o.Remaining) {
		return nil, false
	}
	return o.Remaining, true
}

// HasRemaining returns a boolean if a field has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) HasRemaining() bool {
	if o != nil && !IsNil(o.Remaining) {
		return true
	}

	return false
}

// SetRemaining gets a reference to the given int32 and assigns it to the Remaining field.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetRemaining(v int32) {
	o.Remaining = &v
}

// GetDestroyed returns the Destroyed field value if set, zero value otherwise.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetDestroyed() bool {
	if o == nil || IsNil(o.Destroyed) {
		var ret bool
		return ret
	}
	return *o.Destroyed
}

// GetDestroyedOk returns a tuple with the Destroyed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetDestroyedOk() (*bool, bool) {
	if o == nil || IsNil(o.Destroyed) {
		return nil, false
	}
	return o.Destroyed, true
}

// HasDestroyed returns a boolean if a field has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) HasDestroyed() bool {
	if o != nil && !IsNil(o.Destroyed) {
		return true
	}

	return false
}

// SetDestroyed gets a reference to the given bool and assigns it to the Destroyed field.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetDestroyed(v bool) {
	o.Destroyed = &v
}

// GetBonuses returns the Bonuses field value if set, zero value otherwise.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetBonuses() []string {
	if o == nil || IsNil(o.Bonuses) {
		var ret []string
		return ret
	}
	return o.Bonuses
}

// GetBonusesOk returns a tuple with the Bonuses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) GetBonusesOk() ([]string, bool) {
	if o == nil || IsNil(o.Bonuses) {
		return nil, false
	}
	return o.Bonuses, true
}

// HasBonuses returns a boolean if a field has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) HasBonuses() bool {
	if o != nil && !IsNil(o.Bonuses) {
		return true
	}

	return false
}

// SetBonuses gets a reference to the given []string and assigns it to the Bonuses field.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) SetBonuses(v []string) {
	o.Bonuses = v
}

func (o ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["target"] = o.Target
	if !IsNil(o.Card) {
		toSerialize["card"] = o.Card
	}
	if !IsNil(o.IncomingDamage) {
		toSerialize["incomingDamage"] = o.IncomingDamage
	}
	toSerialize["damage"] = o.Damage
	if !IsNil(o.EffectiveHp) {
		toSerialize["effectiveHp"] = o.EffectiveHp
	}
	if !IsNil(o.HpBefore) {
		toSerialize["hpBefore"] = o.HpBefore
	}
	if !IsNil(o.HpAfter) {
		toSerialize["hpAfter"] = o.HpAfter
	}
	if !IsNil(o.LpBefore) {
		toSerialize["lpBefore"] = o.LpBefore
	}
	if !IsNil(o.LpAfter) {
		toSerialize["lpAfter"] = o.LpAfter
	}
	if !IsNil(o.Absorbed) {
		toSerialize["absorbed"] = o.Absorbed
	}
	if !IsNil(o.Overflow) {
		toSerialize["overflow"] = o.Overflow
	}
	if !IsNil(o.Remaining) {
		toSerialize["remaining"] = o.Remaining
	}
	if !IsNil(o.Destroyed) {
		toSerialize["destroyed"] = o.Destroyed
	}
	if !IsNil(o.Bonuses) {
		toSerialize["bonuses"] = o.Bonuses
	}
	return toSerialize, nil
}

func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"target",
		"damage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner := _ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner)

	if err != nil {
		return err
	}

	*o = ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner(varApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner)

	return err
}

type NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner struct {
	value *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner
	isSet bool
}

func (v NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) Get() *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner {
	return v.value
}

func (v *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) Set(val *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner(val *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner {
	return &NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner{value: val, isSet: true}
}

func (v NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf2CombatStepsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


