/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiUsersUserIdFollowStatsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiUsersUserIdFollowStatsGet200Response{}

// ApiUsersUserIdFollowStatsGet200Response struct for ApiUsersUserIdFollowStatsGet200Response
type ApiUsersUserIdFollowStatsGet200Response struct {
	Followers int32 `json:"followers"`
	Following int32 `json:"following"`
}

type _ApiUsersUserIdFollowStatsGet200Response ApiUsersUserIdFollowStatsGet200Response

// NewApiUsersUserIdFollowStatsGet200Response instantiates a new ApiUsersUserIdFollowStatsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiUsersUserIdFollowStatsGet200Response(followers int32, following int32) *ApiUsersUserIdFollowStatsGet200Response {
	this := ApiUsersUserIdFollowStatsGet200Response{}
	this.Followers = followers
	this.Following = following
	return &this
}

// NewApiUsersUserIdFollowStatsGet200ResponseWithDefaults instantiates a new ApiUsersUserIdFollowStatsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiUsersUserIdFollowStatsGet200ResponseWithDefaults() *ApiUsersUserIdFollowStatsGet200Response {
	this := ApiUsersUserIdFollowStatsGet200Response{}
	return &this
}

// GetFollowers returns the Followers field value
func (o *ApiUsersUserIdFollowStatsGet200Response) GetFollowers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Followers
}

// GetFollowersOk returns a tuple with the Followers field value
// and a boolean to check if the value has been set.
func (o *ApiUsersUserIdFollowStatsGet200Response) GetFollowersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Followers, true
}

// SetFollowers sets field value
func (o *ApiUsersUserIdFollowStatsGet200Response) SetFollowers(v int32) {
	o.Followers = v
}

// GetFollowing returns the Following field value
func (o *ApiUsersUserIdFollowStatsGet200Response) GetFollowing() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Following
}

// GetFollowingOk returns a tuple with the Following field value
// and a boolean to check if the value has been set.
func (o *ApiUsersUserIdFollowStatsGet200Response) GetFollowingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Following, true
}

// SetFollowing sets field value
func (o *ApiUsersUserIdFollowStatsGet200Response) SetFollowing(v int32) {
	o.Following = v
}

func (o ApiUsersUserIdFollowStatsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiUsersUserIdFollowStatsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["followers"] = o.Followers
	toSerialize["following"] = o.Following
	return toSerialize, nil
}

func (o *ApiUsersUserIdFollowStatsGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"followers",
		"following",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiUsersUserIdFollowStatsGet200Response := _ApiUsersUserIdFollowStatsGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiUsersUserIdFollowStatsGet200Response)

	if err != nil {
		return err
	}

	*o = ApiUsersUserIdFollowStatsGet200Response(varApiUsersUserIdFollowStatsGet200Response)

	return err
}

type NullableApiUsersUserIdFollowStatsGet200Response struct {
	value *ApiUsersUserIdFollowStatsGet200Response
	isSet bool
}

func (v NullableApiUsersUserIdFollowStatsGet200Response) Get() *ApiUsersUserIdFollowStatsGet200Response {
	return v.value
}

func (v *NullableApiUsersUserIdFollowStatsGet200Response) Set(val *ApiUsersUserIdFollowStatsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiUsersUserIdFollowStatsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiUsersUserIdFollowStatsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiUsersUserIdFollowStatsGet200Response(val *ApiUsersUserIdFollowStatsGet200Response) *NullableApiUsersUserIdFollowStatsGet200Response {
	return &NullableApiUsersUserIdFollowStatsGet200Response{value: val, isSet: true}
}

func (v NullableApiUsersUserIdFollowStatsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiUsersUserIdFollowStatsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


