/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiStatsUserIdHistoryGet200ResponseCategoriesValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiStatsUserIdHistoryGet200ResponseCategoriesValue{}

// ApiStatsUserIdHistoryGet200ResponseCategoriesValue struct for ApiStatsUserIdHistoryGet200ResponseCategoriesValue
type ApiStatsUserIdHistoryGet200ResponseCategoriesValue struct {
	CurrentElo int32 `json:"currentElo"`
	Matches int32 `json:"matches"`
	Wins int32 `json:"wins"`
}

type _ApiStatsUserIdHistoryGet200ResponseCategoriesValue ApiStatsUserIdHistoryGet200ResponseCategoriesValue

// NewApiStatsUserIdHistoryGet200ResponseCategoriesValue instantiates a new ApiStatsUserIdHistoryGet200ResponseCategoriesValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiStatsUserIdHistoryGet200ResponseCategoriesValue(currentElo int32, matches int32, wins int32) *ApiStatsUserIdHistoryGet200ResponseCategoriesValue {
	this := ApiStatsUserIdHistoryGet200ResponseCategoriesValue{}
	this.CurrentElo = currentElo
	this.Matches = matches
	this.Wins = wins
	return &this
}

// NewApiStatsUserIdHistoryGet200ResponseCategoriesValueWithDefaults instantiates a new ApiStatsUserIdHistoryGet200ResponseCategoriesValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiStatsUserIdHistoryGet200ResponseCategoriesValueWithDefaults() *ApiStatsUserIdHistoryGet200ResponseCategoriesValue {
	this := ApiStatsUserIdHistoryGet200ResponseCategoriesValue{}
	return &this
}

// GetCurrentElo returns the CurrentElo field value
func (o *ApiStatsUserIdHistoryGet200ResponseCategoriesValue) GetCurrentElo() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentElo
}

// GetCurrentEloOk returns a tuple with the CurrentElo field value
// and a boolean to check if the value has been set.
func (o *ApiStatsUserIdHistoryGet200ResponseCategoriesValue) GetCurrentEloOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentElo, true
}

// SetCurrentElo sets field value
func (o *ApiStatsUserIdHistoryGet200ResponseCategoriesValue) SetCurrentElo(v int32) {
	o.CurrentElo = v
}

// GetMatches returns the Matches field value
func (o *ApiStatsUserIdHistoryGet200ResponseCategoriesValue) GetMatches() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Matches
}

// GetMatchesOk returns a tuple with the Matches field value
// and a boolean to check if the value has been set.
func (o *ApiStatsUserIdHistoryGet200ResponseCategoriesValue) GetMatchesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Matches, true
}

// SetMatches sets field value
func (o *ApiStatsUserIdHistoryGet200ResponseCategoriesValue) SetMatches(v int32) {
	o.Matches = v
}

// GetWins returns the Wins field value
func (o *ApiStatsUserIdHistoryGet200ResponseCategoriesValue) GetWins() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Wins
}

// GetWinsOk returns a tuple with the Wins field value
// and a boolean to check if the value has been set.
func (o *ApiStatsUserIdHistoryGet200ResponseCategoriesValue) GetWinsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Wins, true
}

// SetWins sets field value
func (o *ApiStatsUserIdHistoryGet200ResponseCategoriesValue) SetWins(v int32) {
	o.Wins = v
}

func (o ApiStatsUserIdHistoryGet200ResponseCategoriesValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiStatsUserIdHistoryGet200ResponseCategoriesValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["currentElo"] = o.CurrentElo
	toSerialize["matches"] = o.Matches
	toSerialize["wins"] = o.Wins
	return toSerialize, nil
}

func (o *ApiStatsUserIdHistoryGet200ResponseCategoriesValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currentElo",
		"matches",
		"wins",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiStatsUserIdHistoryGet200ResponseCategoriesValue := _ApiStatsUserIdHistoryGet200ResponseCategoriesValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiStatsUserIdHistoryGet200ResponseCategoriesValue)

	if err != nil {
		return err
	}

	*o = ApiStatsUserIdHistoryGet200ResponseCategoriesValue(varApiStatsUserIdHistoryGet200ResponseCategoriesValue)

	return err
}

type NullableApiStatsUserIdHistoryGet200ResponseCategoriesValue struct {
	value *ApiStatsUserIdHistoryGet200ResponseCategoriesValue
	isSet bool
}

func (v NullableApiStatsUserIdHistoryGet200ResponseCategoriesValue) Get() *ApiStatsUserIdHistoryGet200ResponseCategoriesValue {
	return v.value
}

func (v *NullableApiStatsUserIdHistoryGet200ResponseCategoriesValue) Set(val *ApiStatsUserIdHistoryGet200ResponseCategoriesValue) {
	v.value = val
	v.isSet = true
}

func (v NullableApiStatsUserIdHistoryGet200ResponseCategoriesValue) IsSet() bool {
	return v.isSet
}

func (v *NullableApiStatsUserIdHistoryGet200ResponseCategoriesValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiStatsUserIdHistoryGet200ResponseCategoriesValue(val *ApiStatsUserIdHistoryGet200ResponseCategoriesValue) *NullableApiStatsUserIdHistoryGet200ResponseCategoriesValue {
	return &NullableApiStatsUserIdHistoryGet200ResponseCategoriesValue{value: val, isSet: true}
}

func (v NullableApiStatsUserIdHistoryGet200ResponseCategoriesValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiStatsUserIdHistoryGet200ResponseCategoriesValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


