/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"fmt"
)

// TurnPhase Deterministic turn lifecycle phase (RULES.md §4). Each turn executes all 8 phases in order: StartTurn → DeploymentPhase → AttackPhase → AttackResolution → CleanupPhase → ReinforcementPhase → DrawPhase → EndTurn. Player actions are only valid in specific phases.
type TurnPhase string

// List of TurnPhase
const (
	TURNPHASE_START_TURN TurnPhase = "StartTurn"
	TURNPHASE_DEPLOYMENT_PHASE TurnPhase = "DeploymentPhase"
	TURNPHASE_ATTACK_PHASE TurnPhase = "AttackPhase"
	TURNPHASE_ATTACK_RESOLUTION TurnPhase = "AttackResolution"
	TURNPHASE_CLEANUP_PHASE TurnPhase = "CleanupPhase"
	TURNPHASE_REINFORCEMENT_PHASE TurnPhase = "ReinforcementPhase"
	TURNPHASE_DRAW_PHASE TurnPhase = "DrawPhase"
	TURNPHASE_END_TURN TurnPhase = "EndTurn"
)

// All allowed values of TurnPhase enum
var AllowedTurnPhaseEnumValues = []TurnPhase{
	"StartTurn",
	"DeploymentPhase",
	"AttackPhase",
	"AttackResolution",
	"CleanupPhase",
	"ReinforcementPhase",
	"DrawPhase",
	"EndTurn",
}

func (v *TurnPhase) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TurnPhase(value)
	for _, existing := range AllowedTurnPhaseEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TurnPhase", value)
}

// NewTurnPhaseFromValue returns a pointer to a valid TurnPhase
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTurnPhaseFromValue(v string) (*TurnPhase, error) {
	ev := TurnPhase(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TurnPhase: valid values are %v", v, AllowedTurnPhaseEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TurnPhase) IsValid() bool {
	for _, existing := range AllowedTurnPhaseEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TurnPhase value
func (v TurnPhase) Ptr() *TurnPhase {
	return &v
}

type NullableTurnPhase struct {
	value *TurnPhase
	isSet bool
}

func (v NullableTurnPhase) Get() *TurnPhase {
	return v.value
}

func (v *NullableTurnPhase) Set(val *TurnPhase) {
	v.value = val
	v.isSet = true
}

func (v NullableTurnPhase) IsSet() bool {
	return v.isSet
}

func (v *NullableTurnPhase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTurnPhase(val *TurnPhase) *NullableTurnPhase {
	return &NullableTurnPhase{value: val, isSet: true}
}

func (v NullableTurnPhase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTurnPhase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

