/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/RULES.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/EVENT_SCHEMAS.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 0.5.0-rev.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf{}

// MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf struct for MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf
type MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf struct {
	Card MatchesIdSimulatePost200ResponsePreStatePlayersInnerHandInner `json:"card"`
	Position MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOfPosition `json:"position"`
	// Current hit points. Equals card value at deployment. Reduced by incoming damage during attack resolution. Card is destroyed when reduced to 0 (subject to destruction eligibility rules §10-11).
	CurrentHp int32 `json:"currentHp"`
	// Whether the card is face-down. In standard play, all deployed cards are face-up (false). See §21.2.
	FaceDown bool `json:"faceDown"`
}

type _MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf

// NewMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf instantiates a new MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf(card MatchesIdSimulatePost200ResponsePreStatePlayersInnerHandInner, position MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOfPosition, currentHp int32, faceDown bool) *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf {
	this := MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf{}
	this.Card = card
	this.Position = position
	this.CurrentHp = currentHp
	this.FaceDown = faceDown
	return &this
}

// NewMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOfWithDefaults instantiates a new MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOfWithDefaults() *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf {
	this := MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf{}
	return &this
}

// GetCard returns the Card field value
func (o *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) GetCard() MatchesIdSimulatePost200ResponsePreStatePlayersInnerHandInner {
	if o == nil {
		var ret MatchesIdSimulatePost200ResponsePreStatePlayersInnerHandInner
		return ret
	}

	return o.Card
}

// GetCardOk returns a tuple with the Card field value
// and a boolean to check if the value has been set.
func (o *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) GetCardOk() (*MatchesIdSimulatePost200ResponsePreStatePlayersInnerHandInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Card, true
}

// SetCard sets field value
func (o *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) SetCard(v MatchesIdSimulatePost200ResponsePreStatePlayersInnerHandInner) {
	o.Card = v
}

// GetPosition returns the Position field value
func (o *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) GetPosition() MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOfPosition {
	if o == nil {
		var ret MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOfPosition
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) GetPositionOk() (*MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOfPosition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) SetPosition(v MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOfPosition) {
	o.Position = v
}

// GetCurrentHp returns the CurrentHp field value
func (o *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) GetCurrentHp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentHp
}

// GetCurrentHpOk returns a tuple with the CurrentHp field value
// and a boolean to check if the value has been set.
func (o *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) GetCurrentHpOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentHp, true
}

// SetCurrentHp sets field value
func (o *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) SetCurrentHp(v int32) {
	o.CurrentHp = v
}

// GetFaceDown returns the FaceDown field value
func (o *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) GetFaceDown() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FaceDown
}

// GetFaceDownOk returns a tuple with the FaceDown field value
// and a boolean to check if the value has been set.
func (o *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) GetFaceDownOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FaceDown, true
}

// SetFaceDown sets field value
func (o *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) SetFaceDown(v bool) {
	o.FaceDown = v
}

func (o MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["card"] = o.Card
	toSerialize["position"] = o.Position
	toSerialize["currentHp"] = o.CurrentHp
	toSerialize["faceDown"] = o.FaceDown
	return toSerialize, nil
}

func (o *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"card",
		"position",
		"currentHp",
		"faceDown",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf := _MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf)

	if err != nil {
		return err
	}

	*o = MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf(varMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf)

	return err
}

type NullableMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf struct {
	value *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf
	isSet bool
}

func (v NullableMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) Get() *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf {
	return v.value
}

func (v *NullableMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) Set(val *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf(val *MatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) *NullableMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf {
	return &NullableMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf{value: val, isSet: true}
}

func (v NullableMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatchesIdSimulatePost200ResponsePreStatePlayersInnerBattlefieldInnerAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


