/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance{}

// ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance Authoritative ordered arithmetic witness for v3.0 combat. Absent only on historical v1.0/v2.0 entries.
type ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance struct {
	SchemaVersion string `json:"schemaVersion"`
	Steps []ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenanceStepsInner `json:"steps"`
}

type _ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance

// NewApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance instantiates a new ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance(schemaVersion string, steps []ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenanceStepsInner) *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance {
	this := ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance{}
	this.SchemaVersion = schemaVersion
	this.Steps = steps
	return &this
}

// NewApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenanceWithDefaults instantiates a new ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenanceWithDefaults() *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance {
	this := ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance{}
	return &this
}

// GetSchemaVersion returns the SchemaVersion field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) GetSchemaVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) GetSchemaVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchemaVersion, true
}

// SetSchemaVersion sets field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) SetSchemaVersion(v string) {
	o.SchemaVersion = v
}

// GetSteps returns the Steps field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) GetSteps() []ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenanceStepsInner {
	if o == nil {
		var ret []ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenanceStepsInner
		return ret
	}

	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) GetStepsOk() ([]ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenanceStepsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Steps, true
}

// SetSteps sets field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) SetSteps(v []ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenanceStepsInner) {
	o.Steps = v
}

func (o ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["schemaVersion"] = o.SchemaVersion
	toSerialize["steps"] = o.Steps
	return toSerialize, nil
}

func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"schemaVersion",
		"steps",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance := _ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance)

	if err != nil {
		return err
	}

	*o = ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance(varApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance)

	return err
}

type NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance struct {
	value *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance
	isSet bool
}

func (v NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) Get() *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance {
	return v.value
}

func (v *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) Set(val *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance(val *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance {
	return &NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance{value: val, isSet: true}
}

func (v NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1CombatCalculationProvenance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


