/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiMatchesIdReplayGet200ResponseParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMatchesIdReplayGet200ResponseParams{}

// ApiMatchesIdReplayGet200ResponseParams struct for ApiMatchesIdReplayGet200ResponseParams
type ApiMatchesIdReplayGet200ResponseParams struct {
	// Rules semantics version. 1.0 preserves historical behavior; 2.0 preserves corrected combat before liveness draws; 3.0 is the current competitive ruleset.
	SpecVersion string `json:"specVersion"`
	Classic ApiMatchesIdReplayGet200ResponseParamsClassic `json:"classic"`
	// Number of ranks per column (§3.3). Min: 1, Max: 12. rows × columns ≤ 48.
	Rows int32 `json:"rows"`
	// Number of columns per player board (§3.3). Min: 1, Max: 12. rows × columns ≤ 48.
	Columns int32 `json:"columns"`
	// Maximum hand size. Must be ≤ columns (§3.3).
	MaxHandSize int32 `json:"maxHandSize"`
	// Cards drawn at match start. Must equal rows × columns + columns (§3.3).
	InitialDraw int32 `json:"initialDraw"`
	// Enable Classic Ace invulnerability rules (§10).
	ModeClassicAces bool `json:"modeClassicAces"`
	// Enable Classic Face Card destruction hierarchy (§11).
	ModeClassicFaceCards bool `json:"modeClassicFaceCards"`
	// Damage persistence mode (§12).
	ModeDamagePersistence string `json:"modeDamagePersistence"`
	// Enable Classic Deployment: alternating card placement (§5).
	ModeClassicDeployment bool `json:"modeClassicDeployment"`
	// Reserved compatibility flag for non-standard quick-start bootstrap. Canonical v2.0-compliant matches keep this false.
	ModeQuickStart bool `json:"modeQuickStart"`
	ModeSpecialStart ApiMatchesIdReplayGet200ResponseParamsModeSpecialStart `json:"modeSpecialStart"`
	Initiative ApiMatchesIdReplayGet200ResponseParamsInitiative `json:"initiative"`
	ModePassRules ApiMatchesIdReplayGet200ResponseParamsModePassRules `json:"modePassRules"`
}

type _ApiMatchesIdReplayGet200ResponseParams ApiMatchesIdReplayGet200ResponseParams

// NewApiMatchesIdReplayGet200ResponseParams instantiates a new ApiMatchesIdReplayGet200ResponseParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMatchesIdReplayGet200ResponseParams(specVersion string, classic ApiMatchesIdReplayGet200ResponseParamsClassic, rows int32, columns int32, maxHandSize int32, initialDraw int32, modeClassicAces bool, modeClassicFaceCards bool, modeDamagePersistence string, modeClassicDeployment bool, modeQuickStart bool, modeSpecialStart ApiMatchesIdReplayGet200ResponseParamsModeSpecialStart, initiative ApiMatchesIdReplayGet200ResponseParamsInitiative, modePassRules ApiMatchesIdReplayGet200ResponseParamsModePassRules) *ApiMatchesIdReplayGet200ResponseParams {
	this := ApiMatchesIdReplayGet200ResponseParams{}
	this.SpecVersion = specVersion
	this.Classic = classic
	this.Rows = rows
	this.Columns = columns
	this.MaxHandSize = maxHandSize
	this.InitialDraw = initialDraw
	this.ModeClassicAces = modeClassicAces
	this.ModeClassicFaceCards = modeClassicFaceCards
	this.ModeDamagePersistence = modeDamagePersistence
	this.ModeClassicDeployment = modeClassicDeployment
	this.ModeQuickStart = modeQuickStart
	this.ModeSpecialStart = modeSpecialStart
	this.Initiative = initiative
	this.ModePassRules = modePassRules
	return &this
}

// NewApiMatchesIdReplayGet200ResponseParamsWithDefaults instantiates a new ApiMatchesIdReplayGet200ResponseParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMatchesIdReplayGet200ResponseParamsWithDefaults() *ApiMatchesIdReplayGet200ResponseParams {
	this := ApiMatchesIdReplayGet200ResponseParams{}
	return &this
}

// GetSpecVersion returns the SpecVersion field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetSpecVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpecVersion
}

// GetSpecVersionOk returns a tuple with the SpecVersion field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetSpecVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpecVersion, true
}

// SetSpecVersion sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetSpecVersion(v string) {
	o.SpecVersion = v
}

// GetClassic returns the Classic field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetClassic() ApiMatchesIdReplayGet200ResponseParamsClassic {
	if o == nil {
		var ret ApiMatchesIdReplayGet200ResponseParamsClassic
		return ret
	}

	return o.Classic
}

// GetClassicOk returns a tuple with the Classic field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetClassicOk() (*ApiMatchesIdReplayGet200ResponseParamsClassic, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Classic, true
}

// SetClassic sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetClassic(v ApiMatchesIdReplayGet200ResponseParamsClassic) {
	o.Classic = v
}

// GetRows returns the Rows field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetRows() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetRowsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rows, true
}

// SetRows sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetRows(v int32) {
	o.Rows = v
}

// GetColumns returns the Columns field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetColumns() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetColumnsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Columns, true
}

// SetColumns sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetColumns(v int32) {
	o.Columns = v
}

// GetMaxHandSize returns the MaxHandSize field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetMaxHandSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxHandSize
}

// GetMaxHandSizeOk returns a tuple with the MaxHandSize field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetMaxHandSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxHandSize, true
}

// SetMaxHandSize sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetMaxHandSize(v int32) {
	o.MaxHandSize = v
}

// GetInitialDraw returns the InitialDraw field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetInitialDraw() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InitialDraw
}

// GetInitialDrawOk returns a tuple with the InitialDraw field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetInitialDrawOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InitialDraw, true
}

// SetInitialDraw sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetInitialDraw(v int32) {
	o.InitialDraw = v
}

// GetModeClassicAces returns the ModeClassicAces field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModeClassicAces() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ModeClassicAces
}

// GetModeClassicAcesOk returns a tuple with the ModeClassicAces field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModeClassicAcesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModeClassicAces, true
}

// SetModeClassicAces sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetModeClassicAces(v bool) {
	o.ModeClassicAces = v
}

// GetModeClassicFaceCards returns the ModeClassicFaceCards field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModeClassicFaceCards() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ModeClassicFaceCards
}

// GetModeClassicFaceCardsOk returns a tuple with the ModeClassicFaceCards field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModeClassicFaceCardsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModeClassicFaceCards, true
}

// SetModeClassicFaceCards sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetModeClassicFaceCards(v bool) {
	o.ModeClassicFaceCards = v
}

// GetModeDamagePersistence returns the ModeDamagePersistence field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModeDamagePersistence() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModeDamagePersistence
}

// GetModeDamagePersistenceOk returns a tuple with the ModeDamagePersistence field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModeDamagePersistenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModeDamagePersistence, true
}

// SetModeDamagePersistence sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetModeDamagePersistence(v string) {
	o.ModeDamagePersistence = v
}

// GetModeClassicDeployment returns the ModeClassicDeployment field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModeClassicDeployment() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ModeClassicDeployment
}

// GetModeClassicDeploymentOk returns a tuple with the ModeClassicDeployment field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModeClassicDeploymentOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModeClassicDeployment, true
}

// SetModeClassicDeployment sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetModeClassicDeployment(v bool) {
	o.ModeClassicDeployment = v
}

// GetModeQuickStart returns the ModeQuickStart field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModeQuickStart() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ModeQuickStart
}

// GetModeQuickStartOk returns a tuple with the ModeQuickStart field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModeQuickStartOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModeQuickStart, true
}

// SetModeQuickStart sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetModeQuickStart(v bool) {
	o.ModeQuickStart = v
}

// GetModeSpecialStart returns the ModeSpecialStart field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModeSpecialStart() ApiMatchesIdReplayGet200ResponseParamsModeSpecialStart {
	if o == nil {
		var ret ApiMatchesIdReplayGet200ResponseParamsModeSpecialStart
		return ret
	}

	return o.ModeSpecialStart
}

// GetModeSpecialStartOk returns a tuple with the ModeSpecialStart field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModeSpecialStartOk() (*ApiMatchesIdReplayGet200ResponseParamsModeSpecialStart, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModeSpecialStart, true
}

// SetModeSpecialStart sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetModeSpecialStart(v ApiMatchesIdReplayGet200ResponseParamsModeSpecialStart) {
	o.ModeSpecialStart = v
}

// GetInitiative returns the Initiative field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetInitiative() ApiMatchesIdReplayGet200ResponseParamsInitiative {
	if o == nil {
		var ret ApiMatchesIdReplayGet200ResponseParamsInitiative
		return ret
	}

	return o.Initiative
}

// GetInitiativeOk returns a tuple with the Initiative field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetInitiativeOk() (*ApiMatchesIdReplayGet200ResponseParamsInitiative, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Initiative, true
}

// SetInitiative sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetInitiative(v ApiMatchesIdReplayGet200ResponseParamsInitiative) {
	o.Initiative = v
}

// GetModePassRules returns the ModePassRules field value
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModePassRules() ApiMatchesIdReplayGet200ResponseParamsModePassRules {
	if o == nil {
		var ret ApiMatchesIdReplayGet200ResponseParamsModePassRules
		return ret
	}

	return o.ModePassRules
}

// GetModePassRulesOk returns a tuple with the ModePassRules field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseParams) GetModePassRulesOk() (*ApiMatchesIdReplayGet200ResponseParamsModePassRules, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModePassRules, true
}

// SetModePassRules sets field value
func (o *ApiMatchesIdReplayGet200ResponseParams) SetModePassRules(v ApiMatchesIdReplayGet200ResponseParamsModePassRules) {
	o.ModePassRules = v
}

func (o ApiMatchesIdReplayGet200ResponseParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMatchesIdReplayGet200ResponseParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["specVersion"] = o.SpecVersion
	toSerialize["classic"] = o.Classic
	toSerialize["rows"] = o.Rows
	toSerialize["columns"] = o.Columns
	toSerialize["maxHandSize"] = o.MaxHandSize
	toSerialize["initialDraw"] = o.InitialDraw
	toSerialize["modeClassicAces"] = o.ModeClassicAces
	toSerialize["modeClassicFaceCards"] = o.ModeClassicFaceCards
	toSerialize["modeDamagePersistence"] = o.ModeDamagePersistence
	toSerialize["modeClassicDeployment"] = o.ModeClassicDeployment
	toSerialize["modeQuickStart"] = o.ModeQuickStart
	toSerialize["modeSpecialStart"] = o.ModeSpecialStart
	toSerialize["initiative"] = o.Initiative
	toSerialize["modePassRules"] = o.ModePassRules
	return toSerialize, nil
}

func (o *ApiMatchesIdReplayGet200ResponseParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"specVersion",
		"classic",
		"rows",
		"columns",
		"maxHandSize",
		"initialDraw",
		"modeClassicAces",
		"modeClassicFaceCards",
		"modeDamagePersistence",
		"modeClassicDeployment",
		"modeQuickStart",
		"modeSpecialStart",
		"initiative",
		"modePassRules",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiMatchesIdReplayGet200ResponseParams := _ApiMatchesIdReplayGet200ResponseParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiMatchesIdReplayGet200ResponseParams)

	if err != nil {
		return err
	}

	*o = ApiMatchesIdReplayGet200ResponseParams(varApiMatchesIdReplayGet200ResponseParams)

	return err
}

type NullableApiMatchesIdReplayGet200ResponseParams struct {
	value *ApiMatchesIdReplayGet200ResponseParams
	isSet bool
}

func (v NullableApiMatchesIdReplayGet200ResponseParams) Get() *ApiMatchesIdReplayGet200ResponseParams {
	return v.value
}

func (v *NullableApiMatchesIdReplayGet200ResponseParams) Set(val *ApiMatchesIdReplayGet200ResponseParams) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMatchesIdReplayGet200ResponseParams) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMatchesIdReplayGet200ResponseParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMatchesIdReplayGet200ResponseParams(val *ApiMatchesIdReplayGet200ResponseParams) *NullableApiMatchesIdReplayGet200ResponseParams {
	return &NullableApiMatchesIdReplayGet200ResponseParams{value: val, isSet: true}
}

func (v NullableApiMatchesIdReplayGet200ResponseParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMatchesIdReplayGet200ResponseParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


