/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GameViewModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameViewModel{}

// GameViewModel struct for GameViewModel
type GameViewModel struct {
	State ApiMatchesIdActionPost200ResponsePreState `json:"state"`
	ViewerIndex NullableInt32 `json:"viewerIndex"`
	ValidActions []ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction `json:"validActions"`
}

type _GameViewModel GameViewModel

// NewGameViewModel instantiates a new GameViewModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameViewModel(state ApiMatchesIdActionPost200ResponsePreState, viewerIndex NullableInt32, validActions []ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) *GameViewModel {
	this := GameViewModel{}
	this.State = state
	this.ViewerIndex = viewerIndex
	this.ValidActions = validActions
	return &this
}

// NewGameViewModelWithDefaults instantiates a new GameViewModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameViewModelWithDefaults() *GameViewModel {
	this := GameViewModel{}
	return &this
}

// GetState returns the State field value
func (o *GameViewModel) GetState() ApiMatchesIdActionPost200ResponsePreState {
	if o == nil {
		var ret ApiMatchesIdActionPost200ResponsePreState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *GameViewModel) GetStateOk() (*ApiMatchesIdActionPost200ResponsePreState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *GameViewModel) SetState(v ApiMatchesIdActionPost200ResponsePreState) {
	o.State = v
}

// GetViewerIndex returns the ViewerIndex field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *GameViewModel) GetViewerIndex() int32 {
	if o == nil || o.ViewerIndex.Get() == nil {
		var ret int32
		return ret
	}

	return *o.ViewerIndex.Get()
}

// GetViewerIndexOk returns a tuple with the ViewerIndex field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GameViewModel) GetViewerIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ViewerIndex.Get(), o.ViewerIndex.IsSet()
}

// SetViewerIndex sets field value
func (o *GameViewModel) SetViewerIndex(v int32) {
	o.ViewerIndex.Set(&v)
}

// GetValidActions returns the ValidActions field value
func (o *GameViewModel) GetValidActions() []ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction {
	if o == nil {
		var ret []ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction
		return ret
	}

	return o.ValidActions
}

// GetValidActionsOk returns a tuple with the ValidActions field value
// and a boolean to check if the value has been set.
func (o *GameViewModel) GetValidActionsOk() ([]ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValidActions, true
}

// SetValidActions sets field value
func (o *GameViewModel) SetValidActions(v []ApiMatchesIdReplayGet200ResponseTransactionLogInnerAction) {
	o.ValidActions = v
}

func (o GameViewModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameViewModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["viewerIndex"] = o.ViewerIndex.Get()
	toSerialize["validActions"] = o.ValidActions
	return toSerialize, nil
}

func (o *GameViewModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"viewerIndex",
		"validActions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGameViewModel := _GameViewModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGameViewModel)

	if err != nil {
		return err
	}

	*o = GameViewModel(varGameViewModel)

	return err
}

type NullableGameViewModel struct {
	value *GameViewModel
	isSet bool
}

func (v NullableGameViewModel) Get() *GameViewModel {
	return v.value
}

func (v *NullableGameViewModel) Set(val *GameViewModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGameViewModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGameViewModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameViewModel(val *GameViewModel) *NullableGameViewModel {
	return &NullableGameViewModel{value: val, isSet: true}
}

func (v NullableGameViewModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameViewModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


