/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1{}

// ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1 struct for ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1
type ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1 struct {
	Type string `json:"type"`
	// Server-authoritative strategy used to automate a player's remaining deployment turns.
	Strategy string `json:"strategy"`
	Deployments []ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOfQuickDeploymentsInner `json:"deployments"`
	// Current game phase. One of the 8 turn lifecycle phases or gameOver. The gameOver phase is terminal and set when a victory condition is met (LP depletion, card depletion, forfeit, or pass limit).
	PhaseAfter string `json:"phaseAfter"`
}

type _ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1 ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1

// NewApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1 instantiates a new ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1(type_ string, strategy string, deployments []ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOfQuickDeploymentsInner, phaseAfter string) *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1 {
	this := ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1{}
	this.Type = type_
	this.Strategy = strategy
	this.Deployments = deployments
	this.PhaseAfter = phaseAfter
	return &this
}

// NewApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1WithDefaults instantiates a new ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1WithDefaults() *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1 {
	this := ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1{}
	return &this
}

// GetType returns the Type field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) SetType(v string) {
	o.Type = v
}

// GetStrategy returns the Strategy field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) GetStrategy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Strategy
}

// GetStrategyOk returns a tuple with the Strategy field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) GetStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Strategy, true
}

// SetStrategy sets field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) SetStrategy(v string) {
	o.Strategy = v
}

// GetDeployments returns the Deployments field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) GetDeployments() []ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOfQuickDeploymentsInner {
	if o == nil {
		var ret []ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOfQuickDeploymentsInner
		return ret
	}

	return o.Deployments
}

// GetDeploymentsOk returns a tuple with the Deployments field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) GetDeploymentsOk() ([]ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOfQuickDeploymentsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Deployments, true
}

// SetDeployments sets field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) SetDeployments(v []ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOfQuickDeploymentsInner) {
	o.Deployments = v
}

// GetPhaseAfter returns the PhaseAfter field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) GetPhaseAfter() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhaseAfter
}

// GetPhaseAfterOk returns a tuple with the PhaseAfter field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) GetPhaseAfterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhaseAfter, true
}

// SetPhaseAfter sets field value
func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) SetPhaseAfter(v string) {
	o.PhaseAfter = v
}

func (o ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["strategy"] = o.Strategy
	toSerialize["deployments"] = o.Deployments
	toSerialize["phaseAfter"] = o.PhaseAfter
	return toSerialize, nil
}

func (o *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"strategy",
		"deployments",
		"phaseAfter",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1 := _ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1)

	if err != nil {
		return err
	}

	*o = ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1(varApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1)

	return err
}

type NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1 struct {
	value *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1
	isSet bool
}

func (v NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) Get() *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1 {
	return v.value
}

func (v *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) Set(val *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1(val *ApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1 {
	return &NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1{value: val, isSet: true}
}

func (v NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMatchesIdReplayGet200ResponseTransactionLogInnerDetailsOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


