/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiRulesPhasesGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiRulesPhasesGet200ResponseInner{}

// ApiRulesPhasesGet200ResponseInner struct for ApiRulesPhasesGet200ResponseInner
type ApiRulesPhasesGet200ResponseInner struct {
	// Current game phase. One of the 8 turn lifecycle phases or gameOver. The gameOver phase is terminal and set when a victory condition is met (LP depletion, card depletion, forfeit, or pass limit).
	From string `json:"from"`
	// Current game phase. One of the 8 turn lifecycle phases or gameOver. The gameOver phase is terminal and set when a victory condition is met (LP depletion, card depletion, forfeit, or pass limit).
	To string `json:"to"`
	// State machine trigger that causes a phase transition. Player triggers: deploy, attack, pass, reinforce, forfeit. System triggers: deploy:complete, attack:reinforcement, attack:victory, reinforce:complete, system:advance, system:victory, system:init.
	Trigger string `json:"trigger"`
	Action *string `json:"action,omitempty"`
	Description string `json:"description"`
}

type _ApiRulesPhasesGet200ResponseInner ApiRulesPhasesGet200ResponseInner

// NewApiRulesPhasesGet200ResponseInner instantiates a new ApiRulesPhasesGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiRulesPhasesGet200ResponseInner(from string, to string, trigger string, description string) *ApiRulesPhasesGet200ResponseInner {
	this := ApiRulesPhasesGet200ResponseInner{}
	this.From = from
	this.To = to
	this.Trigger = trigger
	this.Description = description
	return &this
}

// NewApiRulesPhasesGet200ResponseInnerWithDefaults instantiates a new ApiRulesPhasesGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiRulesPhasesGet200ResponseInnerWithDefaults() *ApiRulesPhasesGet200ResponseInner {
	this := ApiRulesPhasesGet200ResponseInner{}
	return &this
}

// GetFrom returns the From field value
func (o *ApiRulesPhasesGet200ResponseInner) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *ApiRulesPhasesGet200ResponseInner) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *ApiRulesPhasesGet200ResponseInner) SetFrom(v string) {
	o.From = v
}

// GetTo returns the To field value
func (o *ApiRulesPhasesGet200ResponseInner) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *ApiRulesPhasesGet200ResponseInner) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *ApiRulesPhasesGet200ResponseInner) SetTo(v string) {
	o.To = v
}

// GetTrigger returns the Trigger field value
func (o *ApiRulesPhasesGet200ResponseInner) GetTrigger() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Trigger
}

// GetTriggerOk returns a tuple with the Trigger field value
// and a boolean to check if the value has been set.
func (o *ApiRulesPhasesGet200ResponseInner) GetTriggerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trigger, true
}

// SetTrigger sets field value
func (o *ApiRulesPhasesGet200ResponseInner) SetTrigger(v string) {
	o.Trigger = v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *ApiRulesPhasesGet200ResponseInner) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRulesPhasesGet200ResponseInner) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *ApiRulesPhasesGet200ResponseInner) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *ApiRulesPhasesGet200ResponseInner) SetAction(v string) {
	o.Action = &v
}

// GetDescription returns the Description field value
func (o *ApiRulesPhasesGet200ResponseInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ApiRulesPhasesGet200ResponseInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ApiRulesPhasesGet200ResponseInner) SetDescription(v string) {
	o.Description = v
}

func (o ApiRulesPhasesGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiRulesPhasesGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	toSerialize["trigger"] = o.Trigger
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *ApiRulesPhasesGet200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from",
		"to",
		"trigger",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiRulesPhasesGet200ResponseInner := _ApiRulesPhasesGet200ResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiRulesPhasesGet200ResponseInner)

	if err != nil {
		return err
	}

	*o = ApiRulesPhasesGet200ResponseInner(varApiRulesPhasesGet200ResponseInner)

	return err
}

type NullableApiRulesPhasesGet200ResponseInner struct {
	value *ApiRulesPhasesGet200ResponseInner
	isSet bool
}

func (v NullableApiRulesPhasesGet200ResponseInner) Get() *ApiRulesPhasesGet200ResponseInner {
	return v.value
}

func (v *NullableApiRulesPhasesGet200ResponseInner) Set(val *ApiRulesPhasesGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiRulesPhasesGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiRulesPhasesGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiRulesPhasesGet200ResponseInner(val *ApiRulesPhasesGet200ResponseInner) *NullableApiRulesPhasesGet200ResponseInner {
	return &NullableApiRulesPhasesGet200ResponseInner{value: val, isSet: true}
}

func (v NullableApiRulesPhasesGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiRulesPhasesGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


