/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
)

// checks if the ApiDefaultsGet200ResponseMetaConstraintsRows type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDefaultsGet200ResponseMetaConstraintsRows{}

// ApiDefaultsGet200ResponseMetaConstraintsRows struct for ApiDefaultsGet200ResponseMetaConstraintsRows
type ApiDefaultsGet200ResponseMetaConstraintsRows struct {
	Min *int32 `json:"min,omitempty"`
	Max *int32 `json:"max,omitempty"`
}

// NewApiDefaultsGet200ResponseMetaConstraintsRows instantiates a new ApiDefaultsGet200ResponseMetaConstraintsRows object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDefaultsGet200ResponseMetaConstraintsRows() *ApiDefaultsGet200ResponseMetaConstraintsRows {
	this := ApiDefaultsGet200ResponseMetaConstraintsRows{}
	return &this
}

// NewApiDefaultsGet200ResponseMetaConstraintsRowsWithDefaults instantiates a new ApiDefaultsGet200ResponseMetaConstraintsRows object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDefaultsGet200ResponseMetaConstraintsRowsWithDefaults() *ApiDefaultsGet200ResponseMetaConstraintsRows {
	this := ApiDefaultsGet200ResponseMetaConstraintsRows{}
	return &this
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *ApiDefaultsGet200ResponseMetaConstraintsRows) GetMin() int32 {
	if o == nil || IsNil(o.Min) {
		var ret int32
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200ResponseMetaConstraintsRows) GetMinOk() (*int32, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *ApiDefaultsGet200ResponseMetaConstraintsRows) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given int32 and assigns it to the Min field.
func (o *ApiDefaultsGet200ResponseMetaConstraintsRows) SetMin(v int32) {
	o.Min = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *ApiDefaultsGet200ResponseMetaConstraintsRows) GetMax() int32 {
	if o == nil || IsNil(o.Max) {
		var ret int32
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDefaultsGet200ResponseMetaConstraintsRows) GetMaxOk() (*int32, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *ApiDefaultsGet200ResponseMetaConstraintsRows) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given int32 and assigns it to the Max field.
func (o *ApiDefaultsGet200ResponseMetaConstraintsRows) SetMax(v int32) {
	o.Max = &v
}

func (o ApiDefaultsGet200ResponseMetaConstraintsRows) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDefaultsGet200ResponseMetaConstraintsRows) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Min) {
		toSerialize["min"] = o.Min
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	return toSerialize, nil
}

type NullableApiDefaultsGet200ResponseMetaConstraintsRows struct {
	value *ApiDefaultsGet200ResponseMetaConstraintsRows
	isSet bool
}

func (v NullableApiDefaultsGet200ResponseMetaConstraintsRows) Get() *ApiDefaultsGet200ResponseMetaConstraintsRows {
	return v.value
}

func (v *NullableApiDefaultsGet200ResponseMetaConstraintsRows) Set(val *ApiDefaultsGet200ResponseMetaConstraintsRows) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDefaultsGet200ResponseMetaConstraintsRows) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDefaultsGet200ResponseMetaConstraintsRows) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDefaultsGet200ResponseMetaConstraintsRows(val *ApiDefaultsGet200ResponseMetaConstraintsRows) *NullableApiDefaultsGet200ResponseMetaConstraintsRows {
	return &NullableApiDefaultsGet200ResponseMetaConstraintsRows{value: val, isSet: true}
}

func (v NullableApiDefaultsGet200ResponseMetaConstraintsRows) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDefaultsGet200ResponseMetaConstraintsRows) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


