/*
Phalanx Duel Game Server

Authoritative game server for Phalanx Duel.  ## Authoritative References  - **[RULES.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/gameplay/rules.md)** — Canonical deterministic rules specification (v1.0). All game logic, state machine transitions, suit boundary effects, and victory conditions are defined here. - **[EVENT_SCHEMAS.md](https://github.com/phalanxduel/phalanxduel/blob/main/docs/api/event-schemas.md)** — External event validation schemas. - **[AsyncAPI Spec](/docs/asyncapi.yaml)** — WebSocket protocol specification for real-time gameplay.  ## Discovery Endpoints  - `GET /api/rules/phases` — State machine transition table. Returns all valid phase transitions and their triggers. - `GET /api/cards/manifest` — Card manifest. Returns all possible cards in a standard deck with deterministic stats. - `GET /api/defaults` — Default match parameters and system constraints.  ## State Machine Constraints  A schema-valid action can be semantically invalid if sent in the wrong phase. The `deploy` action is only valid during `DeploymentPhase`. The `attack` and `pass` actions are only valid during `AttackPhase`. The `reinforce` action is only valid during `ReinforcementPhase`. The `forfeit` action is valid in any phase. See the `/api/rules/phases` endpoint for the full transition table.

API version: 0.5.0-rev.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phalanx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiMatchesIdActionPost200ResponsePreStateParamsClassic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMatchesIdActionPost200ResponsePreStateParamsClassic{}

// ApiMatchesIdActionPost200ResponsePreStateParamsClassic struct for ApiMatchesIdActionPost200ResponsePreStateParamsClassic
type ApiMatchesIdActionPost200ResponsePreStateParamsClassic struct {
	// Whether Classic schema binding is active (§3.1).
	Enabled bool `json:"enabled"`
	// Classic schema binding mode (§3.1). strict: all top-level parameters must exactly match the classic template. hybrid: classic values serve as defaults, top-level may override within Global System Constraints.
	Mode string `json:"mode"`
	Battlefield ApiMatchesIdActionPost200ResponsePreStateParamsClassicBattlefield `json:"battlefield"`
	Hand ApiMatchesIdActionPost200ResponsePreStateParamsClassicHand `json:"hand"`
	Start ApiMatchesIdActionPost200ResponsePreStateParamsClassicStart `json:"start"`
	Modes ApiMatchesIdActionPost200ResponsePreStateParamsClassicModes `json:"modes"`
	Initiative ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative `json:"initiative"`
	PassRules ApiMatchesIdActionPost200ResponsePreStateParamsClassicPassRules `json:"passRules"`
}

type _ApiMatchesIdActionPost200ResponsePreStateParamsClassic ApiMatchesIdActionPost200ResponsePreStateParamsClassic

// NewApiMatchesIdActionPost200ResponsePreStateParamsClassic instantiates a new ApiMatchesIdActionPost200ResponsePreStateParamsClassic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMatchesIdActionPost200ResponsePreStateParamsClassic(enabled bool, mode string, battlefield ApiMatchesIdActionPost200ResponsePreStateParamsClassicBattlefield, hand ApiMatchesIdActionPost200ResponsePreStateParamsClassicHand, start ApiMatchesIdActionPost200ResponsePreStateParamsClassicStart, modes ApiMatchesIdActionPost200ResponsePreStateParamsClassicModes, initiative ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative, passRules ApiMatchesIdActionPost200ResponsePreStateParamsClassicPassRules) *ApiMatchesIdActionPost200ResponsePreStateParamsClassic {
	this := ApiMatchesIdActionPost200ResponsePreStateParamsClassic{}
	this.Enabled = enabled
	this.Mode = mode
	this.Battlefield = battlefield
	this.Hand = hand
	this.Start = start
	this.Modes = modes
	this.Initiative = initiative
	this.PassRules = passRules
	return &this
}

// NewApiMatchesIdActionPost200ResponsePreStateParamsClassicWithDefaults instantiates a new ApiMatchesIdActionPost200ResponsePreStateParamsClassic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMatchesIdActionPost200ResponsePreStateParamsClassicWithDefaults() *ApiMatchesIdActionPost200ResponsePreStateParamsClassic {
	this := ApiMatchesIdActionPost200ResponsePreStateParamsClassic{}
	var mode string = "strict"
	this.Mode = mode
	return &this
}

// GetEnabled returns the Enabled field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) SetEnabled(v bool) {
	o.Enabled = v
}

// GetMode returns the Mode field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) SetMode(v string) {
	o.Mode = v
}

// GetBattlefield returns the Battlefield field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetBattlefield() ApiMatchesIdActionPost200ResponsePreStateParamsClassicBattlefield {
	if o == nil {
		var ret ApiMatchesIdActionPost200ResponsePreStateParamsClassicBattlefield
		return ret
	}

	return o.Battlefield
}

// GetBattlefieldOk returns a tuple with the Battlefield field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetBattlefieldOk() (*ApiMatchesIdActionPost200ResponsePreStateParamsClassicBattlefield, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Battlefield, true
}

// SetBattlefield sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) SetBattlefield(v ApiMatchesIdActionPost200ResponsePreStateParamsClassicBattlefield) {
	o.Battlefield = v
}

// GetHand returns the Hand field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetHand() ApiMatchesIdActionPost200ResponsePreStateParamsClassicHand {
	if o == nil {
		var ret ApiMatchesIdActionPost200ResponsePreStateParamsClassicHand
		return ret
	}

	return o.Hand
}

// GetHandOk returns a tuple with the Hand field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetHandOk() (*ApiMatchesIdActionPost200ResponsePreStateParamsClassicHand, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hand, true
}

// SetHand sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) SetHand(v ApiMatchesIdActionPost200ResponsePreStateParamsClassicHand) {
	o.Hand = v
}

// GetStart returns the Start field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetStart() ApiMatchesIdActionPost200ResponsePreStateParamsClassicStart {
	if o == nil {
		var ret ApiMatchesIdActionPost200ResponsePreStateParamsClassicStart
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetStartOk() (*ApiMatchesIdActionPost200ResponsePreStateParamsClassicStart, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) SetStart(v ApiMatchesIdActionPost200ResponsePreStateParamsClassicStart) {
	o.Start = v
}

// GetModes returns the Modes field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetModes() ApiMatchesIdActionPost200ResponsePreStateParamsClassicModes {
	if o == nil {
		var ret ApiMatchesIdActionPost200ResponsePreStateParamsClassicModes
		return ret
	}

	return o.Modes
}

// GetModesOk returns a tuple with the Modes field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetModesOk() (*ApiMatchesIdActionPost200ResponsePreStateParamsClassicModes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Modes, true
}

// SetModes sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) SetModes(v ApiMatchesIdActionPost200ResponsePreStateParamsClassicModes) {
	o.Modes = v
}

// GetInitiative returns the Initiative field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetInitiative() ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative {
	if o == nil {
		var ret ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative
		return ret
	}

	return o.Initiative
}

// GetInitiativeOk returns a tuple with the Initiative field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetInitiativeOk() (*ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Initiative, true
}

// SetInitiative sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) SetInitiative(v ApiMatchesIdActionPost200ResponsePreStateParamsClassicInitiative) {
	o.Initiative = v
}

// GetPassRules returns the PassRules field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetPassRules() ApiMatchesIdActionPost200ResponsePreStateParamsClassicPassRules {
	if o == nil {
		var ret ApiMatchesIdActionPost200ResponsePreStateParamsClassicPassRules
		return ret
	}

	return o.PassRules
}

// GetPassRulesOk returns a tuple with the PassRules field value
// and a boolean to check if the value has been set.
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) GetPassRulesOk() (*ApiMatchesIdActionPost200ResponsePreStateParamsClassicPassRules, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PassRules, true
}

// SetPassRules sets field value
func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) SetPassRules(v ApiMatchesIdActionPost200ResponsePreStateParamsClassicPassRules) {
	o.PassRules = v
}

func (o ApiMatchesIdActionPost200ResponsePreStateParamsClassic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMatchesIdActionPost200ResponsePreStateParamsClassic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["mode"] = o.Mode
	toSerialize["battlefield"] = o.Battlefield
	toSerialize["hand"] = o.Hand
	toSerialize["start"] = o.Start
	toSerialize["modes"] = o.Modes
	toSerialize["initiative"] = o.Initiative
	toSerialize["passRules"] = o.PassRules
	return toSerialize, nil
}

func (o *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"mode",
		"battlefield",
		"hand",
		"start",
		"modes",
		"initiative",
		"passRules",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiMatchesIdActionPost200ResponsePreStateParamsClassic := _ApiMatchesIdActionPost200ResponsePreStateParamsClassic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiMatchesIdActionPost200ResponsePreStateParamsClassic)

	if err != nil {
		return err
	}

	*o = ApiMatchesIdActionPost200ResponsePreStateParamsClassic(varApiMatchesIdActionPost200ResponsePreStateParamsClassic)

	return err
}

type NullableApiMatchesIdActionPost200ResponsePreStateParamsClassic struct {
	value *ApiMatchesIdActionPost200ResponsePreStateParamsClassic
	isSet bool
}

func (v NullableApiMatchesIdActionPost200ResponsePreStateParamsClassic) Get() *ApiMatchesIdActionPost200ResponsePreStateParamsClassic {
	return v.value
}

func (v *NullableApiMatchesIdActionPost200ResponsePreStateParamsClassic) Set(val *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMatchesIdActionPost200ResponsePreStateParamsClassic) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMatchesIdActionPost200ResponsePreStateParamsClassic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMatchesIdActionPost200ResponsePreStateParamsClassic(val *ApiMatchesIdActionPost200ResponsePreStateParamsClassic) *NullableApiMatchesIdActionPost200ResponsePreStateParamsClassic {
	return &NullableApiMatchesIdActionPost200ResponsePreStateParamsClassic{value: val, isSet: true}
}

func (v NullableApiMatchesIdActionPost200ResponsePreStateParamsClassic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMatchesIdActionPost200ResponsePreStateParamsClassic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


