name: Auto Assign
on:
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@2f3e41b009e91b530f973eff2538eca6b555aabb # v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: just3ws
